import json

patch_data = {
  "(%lld)": "(%lld)",
  "(+%lld)": "(+%lld)",
  "%@ (+%lld %@)": "%@ (+%lld %@)",
  "%1$@ %2$lld %3$@": "%1$@ %2$lld %3$@",
  "%lld": "%lld",
  "%1$lld / %2$lld": "%1$lld / %2$lld",
  "%lld / 5": "%lld / 5",
  "%lld %@": "%lld %@",
  "%lld%@": "%lld%@",
  "%lldx": "%lldx",
  "+%lld": "+%lld",
  "+%lld %@": "+%lld %@",
  "h": "小时",
  "Du schiebst finanzielle Entscheidungen vor dir her. Prokrastination kostet dich nicht nur Zeit, sondern bares Geld.": "你在推迟财务决定。拖延不仅浪费时间，还浪费金钱。",
  "Du hast oft keinen Überblick über deine Finanzen. Das führt zu blindem Konsum und Selbstsabotage. Es ist Zeit, die Realität zu akzeptieren.": "你经常对自己的财务状况缺乏了解。这会导致盲目消费和自我破坏。是时候接受现实了。",
  "Du handelst impulsiv und gehst unkalkulierte Risiken ein. Kurzfristiges Dopamin zerstört deinen langfristigen Vermögensaufbau.": "你冲动行事，承担无法估量的风险。短期的多巴胺会破坏你长期的财富积累。",
  "Du forderst dich nicht wirklich heraus. Wenn du immer in der Komfortzone bleibst, stagniert dein Körper.": "你并没有真正挑战自己。如果你总是呆在舒适区，你的身体就会停滞不前。",
  "Du trainierst unregelmäßig. Fitness ist kein Sprint, sondern ein Marathon. Dir fehlt die Beständigkeit.": "你训练不规律。健身不是短跑，而是马拉松。你缺乏持久性。",
  "Du suchst nach Ausreden. Du musst die volle Verantwortung für deine körperliche Verfassung übernehmen.": "你在找借口。你必须对自己的身体状况负全部责任。",
  "Du verlässt dich auf Motivation statt auf Disziplin. Ohne Konsistenz wird kein Wachstum passieren.": "你依赖动力而不是纪律。没有一致性就不会有成长。",
  "Du arbeitest viel, aber nicht klug. Du verschwendest Energie an die falschen Dinge.": "你工作很努力，但不够聪明。你把精力浪费在错误的事情上。",
  "Du planst viel, aber kommst nicht in die Umsetzung. Ideen sind wertlos ohne Exekution.": "你计划很多，但没有付诸实践。没有执行力，想法毫无价值。",
  "Du ernährst dich schlecht oder trinkst zu wenig Wasser. Du gibst deinem Körper nicht das, was er braucht, um zu funktionieren.": "你饮食不佳或喝水太少。你没有给身体提供它需要的能量。",
  "Du ignorierst Alarmsignale deines Körpers und wartest, bis es zu spät ist. Prävention ist günstiger als Heilung.": "你忽视了身体发出的警报信号，直到为时已晚。预防胜于治疗。",
  "Du opferst deinen Schlaf und deine Erholung. Ohne Regeneration brennt dein Körper aus. Du läufst auf Reserve.": "你牺牲了睡眠和休息。没有恢复，你的身体就会崩溃。你在透支自己。",
  "Du lässt dich zu sehr von externen Faktoren steuern. Übernimm die Kontrolle über deine Zeit und Energie.": "你太受外部因素的控制。掌控你的时间和精力。",
  "Du gibst dich mit zu wenig zufrieden. Erhöhe deine Standards, um ein besseres Leben zu führen.": "你太容易满足。提高你的标准，过更好的生活。",
  "Dein Umfeld zieht dich runter. Du bist der Durchschnitt der 5 Menschen, mit denen du die meiste Zeit verbringst.": "你的环境拖累了你。你是与你相处时间最长的5个人的平均值。",
  "Du machst deinen Selbstwert zu stark von der Meinung anderer abhängig. Das macht dich kontrollierbar.": "你把自我价值太依赖于别人的意见。这让你变得容易被控制。",
  "Du lässt dich leicht ablenken und verlierst dein Ziel aus den Augen. Dein Fokus ist aktuell zu reaktiv.": "你很容易分心，偏离目标。你目前的注意力太被动了。",
  "Du konsumierst mehr als du produzierst. Hör auf, dein Leben am Seitenrand zu verbringen.": "你消费的比生产的多。停止在边缘虚度光阴。",
  "Du vermeidest harte Gespräche. Das führt zu angestauten Emotionen und ungelösten Konflikten.": "你逃避艰难的谈话。这会导致情绪积压和未解决的冲突。",
  "Du triffst Entscheidungen aus Angst statt aus Zuversicht. Angst ist ein schlechter Ratgeber.": "你出于恐惧而不是自信做出决定。恐惧是一个糟糕的顾问。",
  "Du hast keine klare Vision für dein Leben. Ohne Ziel wirst du immer nur im Kreis laufen.": "你对生活没有清晰的愿景。没有目标，你永远只会原地打转。",
  "AKTUELL": "当前",
  "abzunehmen": "减肥",
  "aufzubauen": "增肌",
  "body.tracking.add_entry": "添加条目",
  "body.tracking.add_first_entry": "点击 + 添加您的第一个条目。",
  "body.tracking.current": "当前值",
  "body.tracking.delete_target": "删除目标",
  "body.tracking.edit_target": "编辑目标",
  "body.tracking.last_week": "上周",
  "body.tracking.manual_entries": "手动条目",
  "body.tracking.measurements": "身体尺寸",
  "body.tracking.no_data": "无数据",
  "body.tracking.no_target": "没有目标",
  "body.tracking.pace_balanced": "平衡速度",
  "body.tracking.pace_relaxed": "非常轻松的速度",
  "body.tracking.pace_sporty": "运动速度",
  "body.tracking.progress": "进度",
  "body.tracking.remaining": "剩余",
  "body.tracking.target_date": "达成期限",
  "body.tracking.target_date_title": "目标日期",
  "body.tracking.target_measurement_title": "目标值",
  "body.tracking.target_title": "目标",
  "body.tracking.target_weight_title": "目标体重",
  "body.tracking.tip.measurements": "提示：身体尺寸变化缓慢。我们建议每月只测量一次以查看真实进展。",
  "body.tracking.tip.weight": "提示：为了获得最佳结果，我们建议每天早上在同一时间、空腹追踪体重。",
  "body.tracking.unrealistic_desc_adaptive": "为了达到您的目标，您需要每周 %3$@ 大约 %1$.2f %2$@。这太快了。尝试将期限调整为至少 %4$d 周。",
  "body.tracking.unrealistic_goal": "非常有野心的目标",
  "body.tracking.until": "直到 ",
  "body.tracking.weekly_trend": "本周趋势（平均至平均）",
  "body.tracking.weight": "体重",
  "buy.heart.button": "购买心",
  "buy.heart.desc": "已购买心",
  "common.fri": "五",
  "common.mon": "一",
  "common.new": "新",
  "common.ok": "确定",
  "common.sat": "六",
  "common.sun": "日",
  "common.thu": "四",
  "common.tue": "二",
  "common.unit": "单位",
  "common.wed": "三",
  "error.export_failed": "创建备份失败。",
  "error.import_failed": "导入文件失败。",
  "error.screentime.setup_failed": "设置失败。当前可能已激活时间表。",
  "export.pdf.report.completed_habits": "完成的习惯: %lld (与上周相比 %@)",
  "export.pdf.report.daily_focus_item": "%@: %lld 分钟",
  "export.pdf.report.daily_habit_item": "%@: 完成 %lld",
  "export.pdf.report.total_focus_time": "总专注时间: %lld 分钟 (与上周相比 %@)",
  "focus.live_activity.more_tasks": "+ 还有 %@ 个任务",
  "Grovy": "Grovy",
  "igel_pose_liegen": "igel_pose_liegen",
  "igel_pose_rennen": "igel_pose_rennen",
  "igel_pose_schlafen": "igel_pose_schlafen",
  "igel_pose_winken": "igel_pose_winken",
  "month.%lld": "month.%lld",
  "paywall.feature.health.title": "Apple Health 集成",
  "pfad_phase_beschreibung_%@": "pfad_phase_beschreibung_%@",
  "pfad_phase_tag_titel_%@": "pfad_phase_tag_titel_%@",
  "pfad_schwierigkeit_%@": "pfad_schwierigkeit_%@",
  "pfad_schwierigkeit_%@_desc": "pfad_schwierigkeit_%@_desc",
  "plant.create.bad_habit.short": "坏习惯",
  "plant.create.good_habit.short": "好习惯",
  "profile.user.name": "Jannik Schill",
  "prog_strength_d1_t1": "第 1 分钟: %lld %@",
  "prog_strength_d1_t2": "第 2 分钟: %@",
  "prog_strength_d1_t3": "第 3 分钟: 30秒 支撑/倒立",
  "prog_strength_d2_t1": "第 1 分钟: %@",
  "prog_strength_d2_t2": "第 2 分钟: %lld 自重划船",
  "prog_strength_d2_t3": "第 3 分钟: 15-20 抬腿",
  "prog_strength_d2_title": "拉与核心",
  "prog_strength_d3_t3": "3x 15 深蹲跳收尾",
  "prog_strength_d5_t1": "第 1 分钟: %lld %@",
  "prog_strength_d5_t2": "第 2 分钟: %lld 深蹲",
  "prog_strength_d5_t3": "第 3 分钟: 40秒 平板支撑 / L-Sit",
  "prog_strength_d6_title": "代谢调节",
  "prog_strength_dips": "%lld 臂屈伸",
  "prog_strength_lunge_norm": "弓步",
  "prog_strength_pull_norm": "%lld 引体向上",
  "prog_strength_pull_strict": "%lld 严格引体向上",
  "prog_strength_pushup_archer": "射手俯卧撑",
  "prog_strength_pushup_strict": "严格俯卧撑",
  "prog_strength_rows_10": "10 自重划船",
  "prog_strength_run_200": "200米",
  "prog_strength_run_300": "300米",
  "prog_strength_run_400": "400米",
  "rarity.%@": "rarity.%@",
  "s": "秒",
  "shop.category.label": "类别",
  "shop.tab.items.new": "坏习惯",
  "shop.tab.plants.new": "好习惯",
  "smart.weekly.desc.consistent": "太棒了！您不仅表现出强大的量，而且每天都保持极其稳定的表现。您的习惯几乎没有波动——您已经掌握了自己的系统。",
  "smart.weekly.desc.fluctuating": "这周您的节奏非常不稳定。有些日子您非常高效，而在其他日子一切都崩溃了。试着下周不要做所有的事，而是每天做一点。",
  "smart.weekly.desc.insufficient": "本周继续积累更多的专注时间或完成习惯，以获得对您节奏的真实分析。每一天都很重要！",
  "smart.weekly.desc.stable_low": "虽然完成任务的绝对数量仍然很少，但您的一致性很好。您避免了极端的波动，这是长期习惯的完美基础。下周温和地在此基础上再接再厉。",
  "smart.weekly.tip.early_bird": "您经常在很晚（大约 %d 点）才完成 '%@'。如果您真的想早起，晚上把手机放在另一个房间，把闹钟调早 30 分钟。",
  "smart.weekly.tip.fallback_good": "您的作息非常稳定！通过继续将习惯固定在固定的时间来保持这种一致性。",
  "smart.weekly.tip.fallback_low": "下周积累更多的专注会议并完成习惯，以获得有关您的节奏的精确提示。",
  "smart.weekly.tip.gaps": "您在 %@ 停了下来，但其他方面都保持一致。为了避免这种中断，将您的习惯与日常生活中的固定锚点结合起来（例如，总是在刷牙后）。",
  "smart.weekly.tip.late_habits": "您在晚上很晚才完成许多习惯。尝试在早上做的第一件事（吃青蛙）就是完成最重要的习惯——然后您在接下来的一天都会感到清醒。",
  "smart.weekly.tip.weekend_drop": "在周末，您的专注时间完全下降。尝试在这些日子里至少进行一次 15 分钟的小型会议，以免失去节奏。",
  "smart.weekly.title.consistent": "铁一般的恒心",
  "smart.weekly.title.fluctuating": "剧烈波动",
  "smart.weekly.title.insufficient": "需要更多数据",
  "smart.weekly.title.stable_low": "坚实的基础",
  "type.routine": "常规",
  "verlauf.analysis.desc.fluctuating": "您在养成这种习惯时的常规仍然不规律。尝试将其与现有习惯结合起来。",
  "verlauf.analysis.desc.low": "这种习惯最近有些睡眠不足。为明天设定一个可行的小目标。",
  "verlauf.analysis.desc.new": "您才刚刚开始！坚持下去，很快就能看到第一个趋势。",
  "verlauf.analysis.desc.pro": "太棒了！您坚持这种习惯。这是一个根深蒂固的常规。",
  "verlauf.analysis.desc.stable": "您很稳定，即使不是每天都很完美。这正是正确的道路！",
  "verlauf.analysis.title.fluctuating": "剧烈波动",
  "verlauf.analysis.title.low": "回来",
  "verlauf.analysis.title.new": "初始阶段",
  "verlauf.analysis.title.pro": "钢铁般的纪律",
  "verlauf.analysis.title.stable": "良好的基础",
  "weather.detail.double": "2x",
  "weekly_report.feedback.desc.consistent": "本周您非常稳定并保持了扎实的时间。一致性是长期成功的关键！",
  "weekly_report.feedback.desc.fluctuating": "您这周有很大的波动。有些日子您全神贯注，而在其他日子您完全不在。下周的目标：专注于您最重要的 2 个习惯。",
  "weekly_report.feedback.desc.pro_base": "令人印象深刻：与上周相比，您的一致性提高了 %@。",
  "weekly_report.feedback.desc.stable_low": "虽然您本周完成的习惯较少，但您每天的活跃度保持不变。这是真实常规的基础。",
  "weekly_report.feedback.title.consistent": "稳定的一周",
  "weekly_report.feedback.title.fluctuating": "多变的表现",
  "weekly_report.feedback.title.pro": "专业人士",
  "weekly_report.feedback.title.stable_low": "稳定的积累",
  "xp_bis_naechste": "距离 %1$@ 还有 %2$d XP"
}

with open("Garten_Simulation/Localizable.xcstrings", "r") as f:
    data = json.load(f)

count = 0
for key, zh_text in patch_data.items():
    if key in data["strings"]:
        if "localizations" not in data["strings"][key]:
            data["strings"][key]["localizations"] = {}
        data["strings"][key]["localizations"]["zh-Hans"] = {"stringUnit": {"state": "translated", "value": zh_text}}
        data["strings"][key]["localizations"]["zh-Hant"] = {"stringUnit": {"state": "translated", "value": zh_text}}
        count += 1

with open("Garten_Simulation/Localizable.xcstrings", "w") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Patched {count} keys for Chinese.")
