// AppStrings.swift
// Single source of truth for all app translations.
// To add a new language, add a new key to each entry's dictionary.
// To add a new string, add a new entry to the `all` dictionary.

enum AppStrings {

    // MARK: - Lookup
    static func get(_ key: String, language: String) -> String {
        guard let entry = all[key] else { return key }
        return entry[language] ?? entry["de"] ?? key
    }

    // MARK: - All Strings
    // Format: "key": ["de": "Deutsch", "en": "English"]
    static let all: [String: [String: String]] = [

        // MARK: General
        "app.name":          ["de": "Garten Simulation",  "en": "Garden Simulation"],
        "button.buy":        ["de": "Kaufen",              "en": "Buy"],
        "button.water":      ["de": "Gießen",              "en": "Water"],
        "button.ok":         ["de": "OK",                  "en": "OK"],
        "button.cancel":     ["de": "Abbrechen",           "en": "Cancel"],
        "button.use":        ["de": "Einsetzen",           "en": "Use"],
        "button.buy_now":    ["de": "JETZT KAUFEN",        "en": "BUY NOW"],
        "button.delete":     ["de": "Entfernen",           "en": "Remove"],

        // MARK: Garden
        "garden.title":                     ["de": "Mein Garten",                       "en": "My Garden"],
        "garden.empty.title":               ["de": "Noch keine Pflanzen",               "en": "No plants yet"],
        "garden.empty.subtitle":            ["de": "Kaufe deine erste Pflanze im Shop", "en": "Buy your first plant in the shop"],
        "garden.powerups":                  ["de": "Meine Power-Ups",                   "en": "My Power-Ups"],
        "garden.trash":                     ["de": "Dekorationen",                      "en": "Decorations"],
        "garden.plant.symbolism.title":     ["de": "Symbolik",                          "en": "Symbolism"],
        "garden.habits.active":             ["de": "aktive Gewohnheiten",               "en": "habits active"],
        "garden.plant.done":                ["de": "ERLEDIGT",                          "en": "DONE"],
        "garden.plant.delete.title":        ["de": "Pflanze entfernen?",                "en": "Remove plant?"],
        "garden.plant.delete.button":       ["de": "PFLANZE LÖSCHEN",                  "en": "DELETE PLANT"],

        // MARK: Shop
        "shop.title":                  ["de": "Shop",                "en": "Shop"],
        "shop.tab.plants":             ["de": "Pflanzen",            "en": "Plants"],
        "shop.tab.items":              ["de": "Gegenstände",         "en": "Items"],
        "Suchen...":                   ["de": "Suchen...",           "en": "Search..."],
        "Power-Ups":                   ["de": "Power-Ups",           "en": "Power-Ups"],
        "Dekorationen":                ["de": "Dekorationen",        "en": "Decorations"],
        "Alle":                        ["de": "Alle",                "en": "All"],
        "Kategorie":                   ["de": "Kategorie",           "en": "Category"],
        "shop.buy.confirm":            ["de": "Wirklich für %d Coins kaufen?",   "en": "Really buy for %d coins?"],
        "shop.buy.insufficient":       ["de": "Du brauchst noch %d Coins mehr",  "en": "You need %d more coins"],
        "shop.buy.success":            ["de": "Gekauft!",            "en": "Purchased!"],
        "shop.owned":                  ["de": "Bereits im Besitz",   "en": "Already owned"],
        "shop.purchases.count":        ["de": "Käufe im Shop",       "en": "Shop Purchases"],
        "shop.item.description":       ["de": "Beschreibung",        "en": "Description"],
        "shop.item.usage":             ["de": "Benutzung",          "en": "Usage"],
        "shop.your_balance":           ["de": "Dein Stand:",         "en": "Your Balance:"],
        "shop.already_owned":          ["de": "Bereits im Besitz",   "en": "Already Owned"],
        "shop.not_enough_coins":       ["de": "Zu wenig Coins",      "en": "Not Enough Coins"],
        "shop.need_more_coins":        ["de": "Du brauchst noch %d Coins mehr.", "en": "You need %d more coins."],
        "shop.trash_item_subtitle":    ["de": "Dekoration",          "en": "Decoration"],
        "shop.purchase_success.title": ["de": "Gekauft! 🎉",         "en": "Purchased! 🎉"],
        "shop.purchase_success.awesome":["de": "Super!",             "en": "Awesome!"],
        "shop.item.sell":              ["de": "Gegenstand verkaufen", "en": "Sell Item"],

        // MARK: Tags & Categories
        "category.fitness":      ["de": "Fitness",          "en": "Fitness"],
        "category.nutrition":    ["de": "Ernährung",        "en": "Nutrition"],
        "category.endurance":    ["de": "Ausdauer",         "en": "Endurance"],
        "category.learning":     ["de": "Lernen",           "en": "Learning"],
        "category.mentalHealth": ["de": "Mental Health",    "en": "Mental Health"],
        "category.lifestyle":    ["de": "Lifestyle",        "en": "Lifestyle"],
        "category.noAddiction":  ["de": "Suchtfreiheit",    "en": "Addiction-Free"],
        "category.hygiene":      ["de": "Hygiene",          "en": "Hygiene"],
        "category.finance":      ["de": "Finanzen",         "en": "Finance"],
        "category.mindfulness":  ["de": "Achtsamkeit",      "en": "Mindfulness"],
        "category.sleep":        ["de": "Schlaf",           "en": "Sleep"],
        "category.productivity": ["de": "Produktivität",    "en": "Productivity"],
        "category.creativity":   ["de": "Kreativität",      "en": "Creativity"],
        "category.social":       ["de": "Soziales",         "en": "Social"],
        "Gewöhnlich":       ["de": "Gewöhnlich",       "en": "Common"],
        "Selten":           ["de": "Selten",           "en": "Rare"],
        "Episch":           ["de": "Episch",           "en": "Epic"],
        "Legendär":         ["de": "Legendär",         "en": "Legendary"],
        "DEKO":             ["de": "DEKO",             "en": "DECOR"],
        "PLANT":            ["de": "PFLANZE",          "en": "PLANT"],
        "POWER-UP":         ["de": "POWER-UP",          "en": "POWER-UP"],
        "common":           ["de": "Gewöhnlich",       "en": "Common"],
        "rare":             ["de": "Selten",           "en": "Rare"],
        "epic":             ["de": "Episch",           "en": "Epic"],
        "legendary":        ["de": "Legendär",         "en": "Legendary"],

        // MARK: Rarity
        "rarity.bronze":  ["de": "Bronze",  "en": "Bronze"],
        "rarity.silber":  ["de": "Silber",  "en": "Silver"],
        "rarity.gold":    ["de": "Gold",    "en": "Gold"],
        "rarity.diamant": ["de": "Diamant", "en": "Diamond"],

        // MARK: Streak
        "streak.days":     ["de": "%d Tage",             "en": "%d Days"],
        "streak.lost":     ["de": "Streak verloren",     "en": "Streak lost"],
        "streak.complete": ["de": "Alle Pflanzen gegossen!", "en": "All plants watered!"],
        "streak.singular.label": ["de": "Tag",           "en": "Day"],
        "streak.plural.label":   ["de": "Tage",          "en": "Days"],

        "streak.view.title":           ["de": "Streak",              "en": "Streak"],
        "streak.view.weekly_overview": ["de": "Wochenübersicht",      "en": "Weekly Overview"],
        "streak.view.see_more":        ["de": "Siehe mehr",           "en": "See more"],
        "streak.view.see_less":        ["de": "Weniger",              "en": "See less"],
        "streak.popup.new_record":     ["de": "Tag!",                "en": "Day!"],


        // MARK: Profile
        "profile.title":                     ["de": "Profil",                                "en": "Profile"],
        "profile.coins":                     ["de": "Coins",                                 "en": "Coins"],
        "profile.plants":                    ["de": "Pflanzen",                              "en": "Plants"],
        "profile.streak":                    ["de": "Tage",                                  "en": "Days"],
        "profile.achievements":              ["de": "Erfolge",                               "en": "Achievements"],
        "profile.achievements.empty":        ["de": "Noch keine Erfolge freigeschaltet",     "en": "No achievements unlocked yet"],
        "profile.user.name":                 ["de": "Jannik Schill",                         "en": "Jannik Schill"],
        "profile.achievements.subtitle":     ["de": "Dein Trophäen-Schrank",                "en": "Your Trophy Cabinet"],
        "profile.achievements.unlocked":     ["de": "Erfolge freigeschaltet",               "en": "Achievements Unlocked"],
        "profile.achievements.locked_desc":  ["de": "Noch nicht freigeschaltet",            "en": "Not yet unlocked"],
        "profile.coins.available":           ["de": "Coins verfügbar",                       "en": "Coins Available"],
        "profile.coins.total":               ["de": "Gesamtstand",                           "en": "Total Balance"],
        "profile.coins.earned":              ["de": "Verdient (gesamt)",                     "en": "Earned (Total)"],
        "profile.coins.spent":               ["de": "Ausgegeben",                            "en": "Spent"],
        "profile.coins.how_to_earn":         ["de": "SO VERDIENST DU COINS",                "en": "HOW TO EARN COINS"],
        "profile.coins.tip.habit":           ["de": "Gewohnheit erledigen",                  "en": "Complete a habit"],
        "profile.coins.tip.streak":          ["de": "7-Tage Streak",                         "en": "7-Day Streak"],
        "profile.coins.tip.levelup":         ["de": "Level Up",                              "en": "Level Up"],
        "profile.coins.tip.watering":        ["de": "Alle Pflanzen gießen",                  "en": "Water all plants"],
        "profile.plants.subtitle":           ["de": "Pflanzen in deinem Garten",             "en": "Plants in your garden"],
        "profile.plants.list":               ["de": "MEINE PFLANZEN",                        "en": "MY PLANTS"],
        "profile.xp.earned":                 ["de": "Verdiente XP",                          "en": "XP Earned"],
        "profile.xp.total":                  ["de": "Gesamt XP",                            "en": "Total XP"],
        "profile.xp.max":                    ["de": "Meiste XP",                             "en": "Most XP"],
        "profile.streak.best":               ["de": "Bester Streak",                         "en": "Best Streak"],
        "profile.streak.best_short":         ["de": "%d Max",                                "en": "%d Max"],
        "profile.level.max":                 ["de": "Max Level!",                            "en": "Max Level!"],
        "profile.inventory":                 ["de": "Inventar",                              "en": "Inventory"],
        "profile.inventory.plants":          ["de": "Pflanzen",                              "en": "Plants"],
        "profile.inventory.powerups":        ["de": "Power-Ups",                             "en": "Power-Ups"],
        "profile.inventory.decorations":     ["de": "Dekorationen",                          "en": "Decorations"],
        "profile.inventory.total_exchanged": ["de": "Shop-Austausche",                      "en": "Shop Exchanges"],
        "profile.transactions.empty":        ["de": "Noch keine Transaktionen",              "en": "No transactions yet"],

        // MARK: Common
        "common.details": ["de": "DETAILS",  "en": "DETAILS"],
        "common.history": ["de": "VERLAUF",  "en": "HISTORY"],
        "common.total":   ["de": "Gesamt",   "en": "Total"],
        "common.active":  ["de": "Aktiv",    "en": "Active"],
        "common.of":      ["de": "von",      "en": "of"],
        "common.done":    ["de": "FERTIG",   "en": "DONE"],

        // MARK: Level Up & Weather
        "level_up.title":    ["de": "STUFEN-AUFSTIEG! 🎉", "en": "LEVEL UP! 🎉"],
        "level_up.subtitle": ["de": "Dein Garten ist jetzt", "en": "Your garden is now"],
        "weather.new_event": ["de": "Neues Wetter-Event!",   "en": "New Weather Event!"],
        "weather.today_is":  ["de": "Heute gilt",            "en": "Today is"],

        // Weather Event Titles
        "weather.normal.title":  ["de": "Ruhiger Tag",        "en": "Calm Day"],
        "weather.duerre.title":  ["de": "Dürre-Alarm!",       "en": "Drought Alert!"],
        "weather.schnee.title":  ["de": "Frostwarnung",       "en": "Frost Warning"],
        "weather.sturm.title":   ["de": "Sturm zieht auf",    "en": "Storm Approaching"],
        "weather.perfekt.title": ["de": "Perfektes Wetter!",  "en": "Perfect Weather!"],

        // Weather Event Subtitles
        "weather.normal.subtitle":  ["de": "Alles wächst nach Plan",       "en": "Everything grows as planned"],
        "weather.duerre.subtitle":  ["de": "Doppeltes Gießen nötig!",      "en": "Double watering required!"],
        "weather.schnee.subtitle":  ["de": "Nur 50% Belohnung heute",      "en": "Only 50% reward today"],
        "weather.sturm.subtitle":   ["de": "Schwache Pflanzen in Gefahr!", "en": "Weak plants in danger!"],
        "weather.perfekt.subtitle": ["de": "Doppelte Belohnung heute!",    "en": "Double reward today!"],

        // Weather Detail Card Labels
        "weather.detail.gems":      ["de": "GEMS",           "en": "GEMS"],
        "weather.detail.watering":  ["de": "GIESSEN",        "en": "WATERING"],
        "weather.detail.normal":    ["de": "Normal",         "en": "Normal"],
        "weather.detail.double":    ["de": "2x",             "en": "2x"],
        "weather.detail.half":      ["de": "0.5x",           "en": "0.5x"],
        "weather.detail.difficult": ["de": "Erschwert",      "en": "Difficult"],

        // Weather Detail Rules
        "weather.rule.normal":      ["de": "Alles läuft normal. Einmal gießen reicht.", "en": "Everything is normal. Watering once is enough."],
        "weather.rule.duerre":      ["de": "Dürre-Alarm: Du musst heute zweimal gießen.", "en": "Drought Alert: You must water twice today."],
        "weather.rule.schnee":      ["de": "Frost: Du bekommst nur halbe Gems.", "en": "Frost: You only get half the gems."],
        "weather.rule.sturm":       ["de": "Sturm: Empfindliche Pflanzen verlieren schneller an Level.", "en": "Storm: Sensitive plants lose levels faster."],
        "weather.rule.perfekt":     ["de": "Perfektes Wetter: Heute gibt es doppelte Gems.", "en": "Perfect Weather: Today you get double gems."],


        // MARK: Settings
        "settings.title":                   ["de": "Einstellungen",               "en": "Settings"],
        "settings.done":                    ["de": "Fertig",                       "en": "Done"],
        "settings.section.personalization": ["de": "Personalisierung",            "en": "Personalization"],
        "settings.section.general":         ["de": "Allgemein",                   "en": "General"],
        "settings.section.privacy":         ["de": "Datenschutz & Sicherheit",    "en": "Privacy & Security"],
        "settings.section.support":         ["de": "Unterstützung",               "en": "Support"],
        "settings.language":                ["de": "Sprache",                     "en": "Language"],
        "settings.language.de":             ["de": "Deutsch",                     "en": "German"],
        "settings.language.en":             ["de": "Englisch",                    "en": "English"],
        "settings.audio":                   ["de": "Audio & Sounds",              "en": "Audio & Sounds"],
        "settings.haptic":                  ["de": "Haptik Feedback",             "en": "Haptic Feedback"],
        "settings.notifications":           ["de": "Benachrichtigungen",          "en": "Notifications"],
        "settings.privacy_settings":        ["de": "Datenschutz-Einstellungen",   "en": "Privacy Settings"],
        "settings.terms":                   ["de": "Nutzungsbedingungen",         "en": "Terms of Service"],
        "settings.export":                  ["de": "Daten exportieren",           "en": "Export Data"],
        "settings.import":                  ["de": "Daten importieren",           "en": "Import Data"],
        "settings.contact":                 ["de": "Support kontaktieren",        "en": "Contact Support"],
        "settings.share":                   ["de": "App weiterempfehlen",         "en": "Recommend App"],
        "settings.delete_account":          ["de": "ACCOUNT LÖSCHEN",            "en": "DELETE ACCOUNT"],
        "settings.delete_warning":          ["de": "Diese Aktion kann nicht rückgängig gemacht werden.", "en": "This action cannot be undone."],
        "settings.understood":              ["de": "Verstanden",                  "en": "Understood"],
        "settings.action.irreversible":     ["de": "Diese Aktion kann nicht rückgängig gemacht werden.", "en": "This action cannot be undone."],
        "settings.export.desc":             ["de": "Möchten Sie alle Ihre Daten exportieren? Sie erhalten eine Datei mit allen Ihren Pflanzen und Fortschritten.", "en": "Do you want to export all your data? You will receive a file with all your plants and progress."],
        "settings.export.action":           ["de": "Export starten",              "en": "Start Export"],
        "settings.import.desc":             ["de": "Möchten Sie Daten importieren? Dies überschreibt Ihre aktuellen Fortschritte.", "en": "Do you want to import data? This will overwrite your current progress."],
        "settings.import.action":           ["de": "Import starten",              "en": "Start Import"],
        "settings.contact.desc":            ["de": "Haben Sie Fragen oder Probleme? Unser Support-Team hilft Ihnen gerne weiter.", "en": "Do you have questions or problems? Our support team will be happy to help you."],
        "settings.contact.action":          ["de": "Support öffnen",              "en": "Open Support"],
        "settings.share.desc":              ["de": "Gefällt Ihnen die Garten-Simulation? Teilen Sie sie mit Ihren Freunden!", "en": "Do you like the Garden Simulation? Share it with your friends!"],
        "settings.share.action":            ["de": "App teilen",                  "en": "Share App"],
        "settings.privacy.desc":            ["de": "Hier findest du alle Informationen zu den Datenschutzbestimmungen.", "en": "Here you can find all information about the privacy policy."],
        "settings.terms.desc":              ["de": "Hier findest du alle Informationen zu den Nutzungsbedingungen.", "en": "Here you can find all information about the terms of service."],
        
        // Support Form
        "support.title":                    ["de": "Support kontaktieren",        "en": "Contact Support"],
        "support.subject":                  ["de": "Betreff",                     "en": "Subject"],
        "support.reason":                   ["de": "Grund",                      "en": "Reason"],
        "support.description":              ["de": "Beschreibung",                "en": "Description"],
        "support.email":                    ["de": "Deine E-Mail-Adresse",        "en": "Your Email Address"],
        "support.send":                     ["de": "Nachricht senden",            "en": "Send Message"],
        "support.desc":                     ["de": "Beschreibe dein Anliegen so genau wie möglich.", "en": "Describe your request as precisely as possible."],
        "support.success.title":            ["de": "Gesendet!",                   "en": "Sent!"],
        "support.success.msg":              ["de": "Deine Nachricht wurde an jannik.schill.2010@gmail.com gesendet. Wir melden uns bald!", "en": "Your message was sent to jannik.schill.2010@gmail.com. We'll get back to you soon!"],
        "support.reason.general":           ["de": "Allgemeines",                "en": "General"],
        "support.reason.bug":               ["de": "Fehler melden",               "en": "Report a Bug"],
        "support.reason.feedback":          ["de": "Feedback / Vorschlag",        "en": "Feedback / Suggestion"],
        "support.reason.question":          ["de": "Frage",                      "en": "Question"],
        "support.email.desc":               ["de": "Wir nutzen diese Adresse nur, um dir zu antworten.", "en": "We only use this address to respond to you."],
        "settings.section.display":         ["de": "ANZEIGE",                     "en": "DISPLAY"],
        "settings.display.mode":            ["de": "Anzeigemodus",                "en": "Display Mode"],
        "settings.display.mode.desc":       ["de": "Wähle, ob der Name der Pflanze oder die verknüpfte Gewohnheit im Garten angezeigt werden soll.", "en": "Choose whether to display the plant name or the linked habit in the garden."],

        // MARK: Achievement Categories
        "category.streak":   ["de": "Streak",    "en": "Streak"],
        "category.daytime":  ["de": "Tageszeit", "en": "Time of Day"],
        "category.plants":   ["de": "Pflanzen",  "en": "Plants"],
        "category.coins":    ["de": "Coins",     "en": "Coins"],

        // MARK: Achievements – Streak
        "achievement.streak3.title":   ["de": "Erste Schritte",    "en": "First Steps"],
        "achievement.streak3.desc":    ["de": "3 Tage Streak",     "en": "3 Day Streak"],
        "achievement.streak7.title":   ["de": "Eine Woche",        "en": "One Week"],
        "achievement.streak7.desc":    ["de": "7 Tage Streak",     "en": "7 Day Streak"],
        "achievement.streak30.title":  ["de": "Monats-Krieger",    "en": "Month Warrior"],
        "achievement.streak30.desc":   ["de": "30 Tage Streak",    "en": "30 Day Streak"],
        "achievement.streak100.title": ["de": "Legende",           "en": "Legend"],
        "achievement.streak100.desc":  ["de": "100 Tage Streak",   "en": "100 Day Streak"],

        // MARK: Achievements – Coins
        "achievement.coin100.title":   ["de": "Erstes Taschengeld", "en": "First Pocket Money"],
        "achievement.coin100.desc":    ["de": "100 Coins gesammelt","en": "Collected 100 Coins"],
        "achievement.coin1000.title":  ["de": "Sparfuchs",          "en": "Money Saver"],
        "achievement.coin1000.desc":   ["de": "1.000 Coins gesammelt", "en": "Collected 1,000 Coins"],
        "achievement.coin5000.title":  ["de": "Reicher Gärtner",   "en": "Rich Gardener"],
        "achievement.coin5000.desc":   ["de": "5.000 Coins gesammelt", "en": "Collected 5,000 Coins"],
        "achievement.coin10000.title": ["de": "Millionär",          "en": "Millionaire"],
        "achievement.coin10000.desc":  ["de": "10.000 Coins gesammelt", "en": "Collected 10,000 Coins"],

        // MARK: Achievements – Plants
        "achievement.pfl1.title":  ["de": "Erster Setzling",  "en": "First Seedling"],
        "achievement.pfl1.desc":   ["de": "1 Pflanze im Garten", "en": "1 plant in the garden"],
        "achievement.pfl5.title":  ["de": "Kleiner Garten",   "en": "Small Garden"],
        "achievement.pfl5.desc":   ["de": "5 Pflanzen im Garten", "en": "5 plants in the garden"],
        "achievement.pfl10.title": ["de": "Grüner Daumen",    "en": "Green Thumb"],
        "achievement.pfl10.desc":  ["de": "10 Pflanzen im Garten", "en": "10 plants in the garden"],
        "achievement.pfl25.title": ["de": "Meister-Gärtner", "en": "Master Gardener"],
        "achievement.pfl25.desc":  ["de": "25 Pflanzen im Garten", "en": "25 plants in the garden"],

        // MARK: Achievements – Time of Day
        "achievement.morgen5.title":  ["de": "Frühaufsteher",      "en": "Early Bird"],
        "achievement.morgen5.desc":   ["de": "5× vor 9 Uhr erledigt", "en": "Done 5× before 9 AM"],
        "achievement.morgen30.title": ["de": "Morgen-Meister",     "en": "Morning Master"],
        "achievement.morgen30.desc":  ["de": "30× vor 9 Uhr erledigt", "en": "Done 30× before 9 AM"],
        "achievement.abend5.title":   ["de": "Nacht-Eule",         "en": "Night Owl"],
        "achievement.abend5.desc":    ["de": "5× nach 20 Uhr erledigt", "en": "Done 5× after 8 PM"],
        "achievement.abend30.title":  ["de": "Mitternachts-Krieger", "en": "Midnight Warrior"],
        "achievement.abend30.desc":   ["de": "30× nach 20 Uhr erledigt", "en": "Done 30× after 8 PM"],

        // MARK: Plants
        "plant.bambus.name":               ["de": "Bambus",           "en": "Bamboo"],
        "plant.bambus.symbolism":          ["de": "Wächst schnell, extrem stabil und schwer zu brechen", "en": "Grows fast, extremely stable and hard to break"],
        "plant.apfelbaum.name":            ["de": "Apfelbaum",        "en": "Apple Tree"],
        "plant.apfelbaum.symbolism":       ["de": "Level 1 = Kern, Level 10 = voller Baum. Klassisch gesund", "en": "Level 1 = seed, Level 10 = full tree. Classic health"],
        "plant.wildgras.name":             ["de": "Wildgras",         "en": "Wild Grass"],
        "plant.wildgras.symbolism":        ["de": "Zäh, regeneriert sich blitzschnell, bedeckt das Spielfeld", "en": "Tough, regenerates lightning fast, covers the field"],
        "plant.eiche.name":                ["de": "Eiche",            "en": "Oak"],
        "plant.eiche.symbolism":           ["de": "Wächst langsam, wird über Jahrzehnte massiv und weise", "en": "Grows slowly, becomes massive and wise over decades"],
        "plant.lotus.name":                ["de": "Lotus",            "en": "Lotus"],
        "plant.lotus.symbolism":           ["de": "Blüht im Schlamm – Ruhe trotz Stress", "en": "Blooms in mud – peace despite stress"],
        "plant.sonnenblume.name":          ["de": "Sonnenblume",      "en": "Sunflower"],
        "plant.sonnenblume.symbolism":     ["de": "Dreht sich immer zur Sonne – Frühaufsteher-Energie", "en": "Always turns to the sun – Early bird energy"],
        "plant.kaktus.name":               ["de": "Kaktus",           "en": "Cactus"],
        "plant.kaktus.symbolism":          ["de": "Überlebt extremste Bedingungen – Kalt duschen", "en": "Survives extreme conditions – Cold showers"],
        "plant.weinrebe.name":             ["de": "Weinrebe",         "en": "Vine"],
        "plant.weinrebe.symbolism":        ["de": "Je länger nüchtern, desto reicher die Ernte", "en": "The longer sober, the richer the harvest"],
        "plant.kirschbaum.name":           ["de": "Kirschbaum",       "en": "Cherry Tree"],
        "plant.kirschbaum.symbolism":      ["de": "Blüht nur, wenn man sich gut um ihn kümmert – Selfcare", "en": "Blooms only with good care – Selfcare"],
        "plant.minzpflanze.name":          ["de": "Minzpflanze",      "en": "Mint Plant"],
        "plant.minzpflanze.symbolism":     ["de": "Frisch, klar, täglich – Zähneputzen & Hygiene", "en": "Fresh, clear, daily – Toothbrushing & Hygiene"],
        "plant.mandelbaum.name":           ["de": "Mandelbaum",       "en": "Almond Tree"],
        "plant.mandelbaum.symbolism":      ["de": "Investition zahlt sich erst später aus – Sparen", "en": "Investment pays off later – Saving"],
        "plant.bambus_schilf.name":        ["de": "Bambus-Schilf",    "en": "Bamboo Reed"],
        "plant.bambus_schilf.symbolism":   ["de": "Flexibel aber unzerbrechlich – Journaling", "en": "Flexible but unbreakable – Journaling"],
        "plant.lavendel.name":             ["de": "Lavendel",         "en": "Lavender"],
        "plant.lavendel.symbolism":        ["de": "Beruhigt und entspannt den Geist – besserer Schlaf", "en": "Calms and relaxes the mind – better sleep"],
        "plant.efeu.name":                 ["de": "Efeu",             "en": "Ivy"],
        "plant.efeu.symbolism":            ["de": "Breitet sich langsam aber stetig aus – tägliches Dehnen", "en": "Spreads slowly but steadily – daily stretching"],
        "plant.aloe_vera.name":            ["de": "Aloe Vera",        "en": "Aloe Vera"],
        "plant.aloe_vera.symbolism":       ["de": "Heilt und regeneriert still im Hintergrund – weniger Handy", "en": "Heals and regenerates silently – less phone time"],
        "plant.erdbeerpflanze.name":       ["de": "Erdbeerpflanze",   "en": "Strawberry Plant"],
        "plant.erdbeerpflanze.symbolism":  ["de": "Kleine Früchte, große Belohnung – Obst & Gemüse essen", "en": "Small fruits, big reward – eating fruit & veg"],
        "plant.zitronenbaum.name":         ["de": "Zitronenbaum",     "en": "Lemon Tree"],
        "plant.zitronenbaum.symbolism":    ["de": "Sauer macht stark – Vitamin C & Immunsystem", "en": "Sour makes power – Vitamin C & Immune system"],
        "plant.weizenfeld.name":           ["de": "Weizenfeld",       "en": "Wheat Field"],
        "plant.weizenfeld.symbolism":      ["de": "Viele kleine Ähren = große Ernte – Deep Work", "en": "Many small ears = big harvest – Deep Work"],
        "plant.chrysantheme.name":         ["de": "Chrysantheme",     "en": "Chrysanthemum"],
        "plant.chrysantheme.symbolism":    ["de": "Ordnung = Blüte – Sauberkeit & Aufräumen", "en": "Order = Bloom – Cleanliness & Tidying"],
        "plant.klee.name":                 ["de": "Klee",             "en": "Clover"],
        "plant.klee.symbolism":            ["de": "Kleines Glück, täglich gefunden – Dankbarkeit", "en": "Small luck, found daily – Gratitude"],

        // MARK: Habit Names (specific habits per plant)
        "habit.krafttraining":       ["de": "Krafttraining",        "en": "Strength Training"],
        "habit.gesund_kochen":       ["de": "Gesund kochen",        "en": "Healthy Cooking"],
        "habit.joggen":              ["de": "Joggen",               "en": "Jogging"],
        "habit.lesen":               ["de": "Lesen",                "en": "Reading"],
        "habit.meditieren":          ["de": "Meditieren",           "en": "Meditation"],
        "habit.frueh_aufstehen":     ["de": "Früh aufstehen",       "en": "Early Rising"],
        "habit.kalt_duschen":        ["de": "Kalt duschen",         "en": "Cold Showers"],
        "habit.kein_alkohol":        ["de": "Kein Alkohol",         "en": "No Alcohol"],
        "habit.selfcare":            ["de": "Selfcare",             "en": "Self Care"],
        "habit.zaehneputzen":        ["de": "Zähneputzen",          "en": "Brushing Teeth"],
        "habit.geld_sparen":         ["de": "Geld sparen",          "en": "Saving Money"],
        "habit.journaling":          ["de": "Journaling",           "en": "Journaling"],
        "habit.schlafroutine":       ["de": "Schlafroutine",        "en": "Sleep Routine"],
        "habit.stretching":          ["de": "Stretching",           "en": "Stretching"],
        "habit.bildschirmzeit":      ["de": "Bildschirmzeit",       "en": "Screen Time"],
        "habit.obst_gemuese":        ["de": "Obst & Gemüse",       "en": "Fruits & Veggies"],
        "habit.wasser_trinken":      ["de": "Wasser trinken",       "en": "Drinking Water"],
        "habit.deep_work":           ["de": "Deep Work",            "en": "Deep Work"],
        "habit.aufraeumen":          ["de": "Aufräumen",            "en": "Tidying Up"],
        "habit.dankbarkeit":         ["de": "Dankbarkeit",          "en": "Gratitude"],

        // MARK: - Game Database - Decorations (formerly Trash)
        "trash.ultra_konsole.name":         ["de": "Gartenbank",          "en": "Garden Bench"],
        "trash.ultra_konsole.desc":         ["de": "Ein gemütlicher Ort zum Verweilen.", "en": "A cozy place to relax."],
        "trash.fast_food_abo.name":          ["de": "Brunnen",             "en": "Fountain"],
        "trash.fast_food_abo.desc":          ["de": "Beruhigendes Geplätscher für deinen Garten. (+1 Coin)", "en": "Calming water sounds for your garden. (+1 Coin)"],
        "trash.endlos_scroll_tv.name":       ["de": "Vogelhäuschen",       "en": "Birdhouse"],
        "trash.endlos_scroll_tv.desc":       ["de": "Zieht zwitschernde Freunde an.", "en": "Attracts chirping friends."],
        "trash.luxus_auto.name":             ["de": "Laterne",             "en": "Lantern"],
        "trash.luxus_auto.desc":             ["de": "Spendet sanftes Licht am Abend.", "en": "Provides soft light in the evening."],
        "trash.party_pass.name":             ["de": "Trittstein-Pfad",      "en": "Stepping Stone Path"],
        "trash.party_pass.desc":             ["de": "Ein schöner Weg durchs Grüne.", "en": "A beautiful path through the greenery."],
        "trash.energy_drink_kiste.name":     ["de": "Gartenzwerg",         "en": "Garden Gnome"],
        "trash.energy_drink_kiste.desc":     ["de": "Ein klassischer Wächter.", "en": "A classic garden protector."],
        "trash.zigaretten_automat.name":     ["de": "Sonnenschirm",        "en": "Sun Umbrella"],
        "trash.zigaretten_automat.desc":     ["de": "Spendet Schatten an heißen Tagen.", "en": "Provides shade on hot days."],
        "trash.online_shopping_app.name":    ["de": "Seerosenteich",       "en": "Lily Pond"],
        "trash.online_shopping_app.desc":    ["de": "Ein Biotop für Wasserfreunde. (+2 Coins)", "en": "A biotope for water lovers. (+2 Coins)"],
        "trash.junk_mail_abo.name":          ["de": "Vogelbad",            "en": "Bird Bath"],
        "trash.junk_mail_abo.desc":          ["de": "Erfrischung für die Vögel.", "en": "A quick refresh for the birds."],
        "trash.nacht_snack_box.name":        ["de": "Holzzaun",            "en": "Wooden Fence"],
        "trash.nacht_snack_box.desc":        ["de": "Grenzt deinen Garten sicher ab.", "en": "Secures your garden boundaries."],
        "trash.alkohol_flatrate.name":       ["de": "Steinstatue",         "en": "Stone Statue"],
        "trash.alkohol_flatrate.desc":       ["de": "Ein Hauch von Kunst und Zeitlosigkeit.", "en": "A touch of art and timelessness."],
        "trash.doomscrolling_handy.name":    ["de": "Windrad",             "en": "Windmill"],
        "trash.doomscrolling_handy.desc":    ["de": "Dreht sich fröhlich im Wind.", "en": "Spins happily in the wind."],
        "trash.binge_streaming.name":        ["de": "Hängematte",          "en": "Hammock"],
        "trash.binge_streaming.desc":        ["de": "Perfekt für ein kleines Schläfchen.", "en": "Perfect for a little nap."],
        "trash.fastfood_lieferdienst.name":  ["de": "Gartenfackel",        "en": "Garden Torch"],
        "trash.fastfood_lieferdienst.desc":  ["de": "Feurige Beleuchtung für die Nacht.", "en": "Fiery lighting for the night."],
        "trash.lootbox_zockerabo.name":      ["de": "Blumenkübel",         "en": "Flower Pot"],
        "trash.lootbox_zockerabo.desc":      ["de": "Zusätzlicher Platz für wilde Blumen.", "en": "Extra space for wild flowers."],
        "trash.luxus_uhr.name":              ["de": "Bienenhaus",          "en": "Bee House"],
        "trash.luxus_uhr.desc":              ["de": "Summende Helfer für die Bestäubung. (+1 Coin)", "en": "Buzzing helpers for pollination. (+1 Coin)"],
        "trash.couch_abo.name":              ["de": "Igelhaus",            "en": "Hedgehog House"],
        "trash.couch_abo.desc":              ["de": "Ein sicheres Quartier für Igel.", "en": "A safe quarter for hedgehogs."],
        "trash.doener_dauerkarte.name":      ["de": "Kiesweg",             "en": "Gravel Path"],
        "trash.doener_dauerkarte.desc":      ["de": "Knirscht so schön beim Drüberlaufen.", "en": "Crunches nicely when walking over it."],
        "trash.negativitaets_feed.name":     ["de": "Brücke",              "en": "Bridge"],
        "trash.negativitaets_feed.desc":     ["de": "Verbindet verschiedene Gartenbereiche.", "en": "Connects different garden areas."],
        "trash.schlaf_killer_koffein.name":  ["de": "Gartenhütte",         "en": "Garden Shed"],
        "trash.schlaf_killer_koffein.desc":  ["de": "Viel Platz für alle deine Werkzeuge.", "en": "Plenty of space for all your tools."],

        // MARK: Power-Ups
        "item.gartenschutz.name":              ["de": "Gartenschutz",        "en": "Garden Protection"],
        "item.gartenschutz.description":       ["de": "Ein schützendes Gartenhaus, das deine Pflanzen 24h vor Frost und Schnee bewahrt.", "en": "A protective garden house that preserves your plants from frost and snow for 24h."],
        "item.wunder_wasser.name":             ["de": "Wunder-Wasser",       "en": "Wonder Water"],
        "item.wunder_wasser.description":      ["de": "Rettet eine vertrocknete Pflanze sofort.", "en": "Rescues a dried plant immediately."],
        "item.waechter_turm.name":             ["de": "Wächter-Turm",        "en": "Guardian Tower"],
        "item.waechter_turm.description":      ["de": "Ein Turm, der eine Pflanze vor dem nächsten Sturm schützt.", "en": "A tower that protects a plant from the next storm."],
        "item.duenger_blitz.name":             ["de": "Dünger-Blitz",        "en": "Fertilizer Blitz"],
        "item.duenger_blitz.description":      ["de": "Verdoppelt XP für die nächsten 3 Erledigungen.", "en": "Doubles XP for the next 3 completions."],
        "item.zauberstab.name":                ["de": "Zauberstab",          "en": "Magic Wand"],
        "item.zauberstab.description":         ["de": "Ein magischer Stab, der 3 Tage lang automatisch das Unkraut wegzaubert.", "en": "A magic wand that automatically removes weeds for 3 days."],
        "item.zeitkapsel.name":                ["de": "Zeitkapsel",          "en": "Time Capsule"],
        "item.zeitkapsel.description":         ["de": "Friert eine Pflanze ein – kein Verfall für 3 Tage.", "en": "Freezes a plant – no decay for 3 days."],
        "item.goldener_schluessel.name":       ["de": "Goldener Schlüssel",  "en": "Golden Key"],
        "item.goldener_schluessel.description": ["de": "Ein wertvoller Schlüssel, der das volle Wachstumspotenzial deines Gartens für eine Woche entriegelt.", "en": "A valuable key that unlocks the full growth potential of your garden for one week."],
        "item.diamant_erde.name":              ["de": "Diamant-Erde",       "en": "Diamond Soil"],
        "item.diamant_erde.description":       ["de": "Permanentes +10% XP für eine Pflanze. Für immer.", "en": "Permanent +10% XP for one plant. Forever."],
        "item.tier_freund.name":               ["de": "Tier-Freund",        "en": "Animal Friend"],
        "item.tier_freund.description":        ["de": "Bestäubt 3 Pflanzen mit einem Mini-Level-Boost.", "en": "Pollinates 3 plants with a mini level boost."],
        "item.gluecks_segen.name":             ["de": "Glücks-Segen",        "en": "Luck's Blessing"],
        "item.gluecks_segen.description":      ["de": "Ein Segen, der 24h lang das Wachstum aller Pflanzen verdoppelt.", "en": "A blessing that doubles the growth of all plants for 24 hours."],

        // MARK: Power-Up Usage Instructions
        "item.gartenschutz.usage":             ["de": "Wird sofort aktiv und bietet deinem Garten einen sicheren Unterschlupf.", "en": "Becomes active immediately and offers your garden a safe shelter."],
        "item.wunder_wasser.usage":            ["de": "Tippe auf eine vertrocknete Pflanze, um sie zu retten.", "en": "Tap on a dried plant to rescue it."],
        "item.waechter_turm.usage":            ["de": "Tippe auf die Pflanze, die du mit dem Turm schützen möchtest.", "en": "Tap on the plant you want to protect with the tower."],
        "item.duenger_blitz.usage":             ["de": "Wird sofort aktiv und verdoppelt deine nächsten XP-Gewinne.", "en": "Becomes active immediately and doubles your next XP gains."],
        "item.zauberstab.usage":               ["de": "Wird sofort aktiv und lässt Unkraut wie von Geisterhand verschwinden.", "en": "Becomes active immediately and makes weeds disappear as if by magic."],
        "item.zeitkapsel.usage":               ["de": "Wird sofort aktiv und stoppt den Verfall aller Pflanzen.", "en": "Becomes active immediately and stops decay for all plants."],
        "item.goldener_schluessel.usage":      ["de": "Wird sofort aktiv und öffnet die Tür zu raschem Wachstum.", "en": "Becomes active immediately and opens the door to rapid growth."],
        "item.diamant_erde.usage":             ["de": "Wird sofort aktiv und verbessert die Bodenqualität.", "en": "Becomes active immediately and improves soil quality."],
        "item.tier_freund.usage":              ["de": "Wird sofort aktiv und ruft kleine Helfer in den Garten.", "en": "Becomes active immediately and calls little helpers to the garden."],
        "item.gluecks_segen.usage":            ["de": "Wird sofort aktiv und segnet deinen Garten mit schnellem Wachstum.", "en": "Becomes active immediately and blesses your garden with rapid growth."],
        "decoration.category.moebel":      ["de": "Möbel",       "en": "Furniture"],
        "decoration.category.wasser":      ["de": "Wasser",      "en": "Water"],
        "decoration.category.tiere":       ["de": "Tiere",       "en": "Animals"],
        "decoration.category.pfade":       ["de": "Pfade",       "en": "Paths"],
        "decoration.category.beleuchtung": ["de": "Beleuchtung", "en": "Lighting"],
        "decoration.category.deko":        ["de": "Deko",        "en": "Decor"],
        "decoration.category.pflanzen":    ["de": "Pflanzen",    "en": "Plants"],

        "achievement.deko1.title": ["de": "Gärtner-Designer", "en": "Garden Designer"],

        "achievement.deko1.desc":  ["de": "Erste Dekoration gekauft", "en": "Bought first decoration"],
        "achievement.deko5.title": ["de": "Vollständiger Garten", "en": "Complete Garden"],
        "achievement.deko5.desc":  ["de": "5 Dekorationen gleichzeitig platziert", "en": "5 decorations placed at once"],

        // MARK: Plant Detail Sheet
        "plant.detail.note":               ["de": "Notiz",                          "en": "Note"],
        "plant.detail.note.placeholder":   ["de": "Schreibe eine Notiz...",         "en": "Write a note..."],
        "plant.detail.note.save":          ["de": "Speichern",                      "en": "Save"],
        "plant.detail.note.edit":           ["de": "Notiz bearbeiten",               "en": "Edit Note"],
        "plant.detail.note.add":            ["de": "Neue Notiz",                     "en": "New Note"],
        "plant.detail.note.add.action":     ["de": "Hinzufügen",                     "en": "Add"],
        "plant.detail.note.delete.confirm": ["de": "Notiz wirklich löschen?",        "en": "Really delete note?"],
        "plant.detail.note.delete.action":  ["de": "Löschen",                        "en": "Delete"],
        "plant.detail.timer":              ["de": "Timer",                          "en": "Timer"],
        "plant.detail.timer.set":          ["de": "Erinnerung setzen",              "en": "Set Reminder"],
        "plant.detail.timer.active":       ["de": "Erinnerung aktiv",               "en": "Reminder active"],
        "plant.detail.timer.delete":       ["de": "Timer löschen",                  "en": "Delete Timer"],
        "plant.detail.timer.cancel.confirm":["de": "Erinnerung wirklich abbrechen?", "en": "Really cancel reminder?"],
        "plant.detail.timer.cancel.action": ["de": "Abbrechen",                      "en": "Cancel"],
        "plant.detail.sell":               ["de": "Pflanze verkaufen",              "en": "Sell Plant"],
        "plant.detail.sell.confirm":       ["de": "Möchtest du diese Pflanze wirklich verkaufen?", "en": "Do you really want to sell this plant?"],
        "plant.detail.sell.action":        ["de": "Verkaufen",                      "en": "Sell"],
        "plant.detail.xp":                 ["de": "XP",                             "en": "XP"],
        "plant.detail.streak":             ["de": "Streak",                         "en": "Streak"],
        "plant.detail.watered":            ["de": "Gegossen",                       "en": "Watered"],

        // MARK: Reset App Data
        "settings.section.danger":         ["de": "GEFAHRENZONE",                   "en": "DANGER ZONE"],
        "settings.reset.title":            ["de": "Alle Daten löschen",             "en": "Delete All Data"],
        "settings.reset.alert.title":      ["de": "App zurücksetzen?",              "en": "Reset App?"],
        "settings.reset.alert.message":     ["de": "Diese Aktion löscht alle deine Pflanzen, Coins und Fortschritte. Das kann nicht rückgängig gemacht werden.", "en": "This action will delete all your plants, coins, and progress. This cannot be undone."],
        "settings.reset.confirm":          ["de": "Alles löschen",                  "en": "Delete Everything"],

        // MARK: Daily Spin
        "dailyspin.title":                 ["de": "Daily Spin",                                      "en": "Daily Spin"],
        "dailyspin.subtitle":              ["de": "Drehe das Rad, um in den Tag zu starten!",        "en": "Spin the wheel to start your day!"],
        "dailyspin.button.spin":           ["de": "RAD DREHEN",                                      "en": "SPIN THE WHEEL"],
        "dailyspin.button.continue":       ["de": "Weiter",                                          "en": "Continue"],
        "dailyspin.weed.danger":           ["de": "Unkraut-Gefahr: %d%%",                            "en": "Weed Risk: %d%%"],
        "dailyspin.result.safe.title":     ["de": "Alles gut!",                                      "en": "All Clear!"],
        "dailyspin.result.safe.subtitle":  ["de": "Dein Garten ist sicher.",                         "en": "Your garden is safe."],
        "dailyspin.result.weed.title":     ["de": "Unkraut entdeckt!",                               "en": "Weed Spotted!"],
        "dailyspin.result.weed.subtitle":  ["de": "%@ braucht deine Aufmerksamkeit.",                "en": "%@ needs your attention."],
        "dailyspin.result.coins.title":    ["de": "+200 Münzen!",                                    "en": "+200 Coins!"],
        "dailyspin.result.coins.subtitle": ["de": "Super Start in den Tag!",                         "en": "Great start to the day!"],
        "dailyspin.powerup.title":         ["de": "Power-Up verfügbar",                              "en": "Power-Up available"],
        "dailyspin.powerup.subtitle":      ["de": "Garantiert Grün — kein Unkraut möglich",          "en": "Guaranteed Green — no weeds possible"],
        "dailyspin.powerup.button":        ["de": "Nutzen",                                          "en": "Use"],
        "dailyspin.no_spins_hint":         ["de": "Du hast deine tägliche Gratis-Drehung bereits genutzt.", "en": "You've already used your daily free spin."],

        // MARK: Spin Buttons
        "spin_button_gratis":              ["de": "Gratis drehen!",                                  "en": "Free Spin!"],
        "spin_button_mit_anzahl":          ["de": "Drehen (%d)",                                     "en": "Spin (%d)"],
        "spin_button_keine":               ["de": "Morgen wieder gratis",                            "en": "Free again tomorrow"],
        "spin_button_later":               ["de": "Später",                                          "en": "Later"],

        // MARK: Stufen Labels
        "stufe.bronze1":                   ["de": "Bronze I",    "en": "Bronze I"],
        "stufe.bronze2":                   ["de": "Bronze II",   "en": "Bronze II"],
        "stufe.bronze3":                   ["de": "Bronze III",  "en": "Bronze III"],
        "stufe.silber1":                   ["de": "Silber I",    "en": "Silver I"],
        "stufe.silber2":                   ["de": "Silber II",   "en": "Silver II"],
        "stufe.silber3":                   ["de": "Silber III",  "en": "Silver III"],
        "stufe.gold1":                     ["de": "Gold I",      "en": "Gold I"],
        "stufe.gold2":                     ["de": "Gold II",     "en": "Gold II"],
        "stufe.gold3":                     ["de": "Gold III",    "en": "Gold III"],
        "stufe.diamant1":                  ["de": "Diamant I",   "en": "Diamond I"],
        "stufe.diamant2":                  ["de": "Diamant II",  "en": "Diamond II"],
        "stufe.diamant3":                  ["de": "Diamant III", "en": "Diamond III"],
        "stufe.naechste.hinweis":          ["de": "Noch %d XP bis %@", "en": "%d XP until %@"],

        // MARK: Achievement System
        "erfolg.erstewoche.name":          ["de": "Erste Woche", "en": "First Week"],
        "erfolg.erstewoche.beschreibung":  ["de": "7 Tage Streak erreicht", "en": "Reached a 7-day streak"],
        "erfolg.legende.name":             ["de": "Legende", "en": "Legend"],
        "erfolg.legende.beschreibung":     ["de": "100 Tage Streak erreicht", "en": "Reached a 100-day streak"],
        "erfolg.jahresring.name":          ["de": "Jahresring", "en": "Yearly Ring"],
        "erfolg.jahresring.beschreibung":  ["de": "365 Tage Streak erreicht", "en": "Reached a 365-day streak"],
        "erfolg.wassermeister.name":       ["de": "Wassermeister", "en": "Water Master"],
        "erfolg.wassermeister.beschreibung": ["de": "100 Mal gegossen", "en": "Watered 100 times"],
        "erfolg.xpsammler.name":           ["de": "XP-Sammler", "en": "XP Collector"],
        "erfolg.xpsammler.beschreibung":   ["de": "500 XP gesammelt", "en": "Collected 500 XP"],
        "erfolg.ersterpflanze.name":        ["de": "Erste Pflanze", "en": "First Plant"],
        "erfolg.ersterpflanze.beschreibung": ["de": "Die erste Pflanze im Garten", "en": "The first plant in your garden"],
        "erfolg.pflanzensammler.name":      ["de": "Pflanzensammler", "en": "Plant Collector"],
        "erfolg.pflanzensammler.beschreibung": ["de": "3 Pflanzen im Garten", "en": "3 plants in your garden"],
        "erfolg.gruenerDaumen.name":       ["de": "Grüner Daumen", "en": "Green Thumb"],
        "erfolg.gruenerDaumen.beschreibung": ["de": "10 Pflanzen im Garten", "en": "10 plants in your garden"],
        "erfolg.gartenprofi.name":         ["de": "Gartenprofi", "en": "Garden Pro"],
        "erfolg.gartenprofi.beschreibung": ["de": "20 Pflanzen im Garten", "en": "20 plants in your garden"],
        "erfolg.ersteMuenze.name":         ["de": "Erste Münze", "en": "First Coin"],
        "erfolg.ersteMuenze.beschreibung": ["de": "Deine erste Münze verdient", "en": "Earned your first coin"],
        "erfolg.muenzmeister.name":        ["de": "Münzmeister", "en": "Coin Master"],
        "erfolg.muenzmeister.beschreibung": ["de": "50 Münzen verdient", "en": "Earned 50 coins"],
        "erfolg.ersterkauf.name":          ["de": "Erster Kauf", "en": "First Purchase"],
        "erfolg.ersterkauf.beschreibung":  ["de": "Dein erster Einkauf im Shop", "en": "Your first shop purchase"],

        // MARK: Achievement Details
        "erfolge.erreicht_am":             ["de": "Erreicht am %@",             "en": "Achieved on %@"],
        "erfolge.beschreibung.titel":      ["de": "WIE DU ES ERREICHT HAST",    "en": "HOW YOU ACHIEVED IT"],
        "erfolge.freigeschaltet":          ["de": "Freigeschaltet",            "en": "Unlocked"],
        "erfolge.fortschritt":             ["de": "Fortschritt",               "en": "Progress"],
    ]
}
