// AppStrings.swift
// Single source of truth for all app translations.
// To add a new language, add a new key to each entry's dictionary.
// To add a new string, add a new entry to the `all` dictionary.

enum AppStrings {

    // MARK: - Lookup
    static func get(_ key: String, language: String) -> String {
        guard let entry = all[key] else { return key }
        return entry[language] ?? entry["de"] ?? key
    }

    // MARK: - All Strings
    // Format: "key": ["de": "Deutsch", "en": "English"]
    static let all: [String: [String: String]] = [

        // MARK: General
        "app.name":          ["de": "Garten Simulation",  "en": "Garden Simulation"],
        "button.buy":        ["de": "Kaufen",              "en": "Buy"],
        "button.water":      ["de": "Gießen",              "en": "Water"],
        "button.ok":         ["de": "OK",                  "en": "OK"],
        "button.cancel":     ["de": "Abbrechen",           "en": "Cancel"],
        "button.use":        ["de": "Einsetzen",           "en": "Use"],
        "button.delete":     ["de": "Entfernen",           "en": "Remove"],

        // MARK: Garden
        "garden.title":                     ["de": "Mein Garten",                       "en": "My Garden"],
        "garden.empty.title":               ["de": "Noch keine Pflanzen",               "en": "No plants yet"],
        "garden.empty.subtitle":            ["de": "Kaufe deine erste Pflanze im Shop", "en": "Buy your first plant in the shop"],
        "garden.powerups":                  ["de": "Meine Power-Ups",                   "en": "My Power-Ups"],
        "garden.trash":                     ["de": "Dekorationen",                      "en": "Decorations"],
        "garden.plant.symbolism.title":     ["de": "Symbolik",                          "en": "Symbolism"],
        "garden.habits.active":             ["de": "aktive Gewohnheiten",               "en": "habits active"],
        "garden.plant.done":                ["de": "ERLEDIGT",                          "en": "DONE"],
        "garden.plant.delete.title":        ["de": "Pflanze entfernen?",                "en": "Remove plant?"],

        // MARK: Shop
        "shop.title":                  ["de": "Shop",                "en": "Shop"],
        "shop.tab.plants":             ["de": "Pflanzen",            "en": "Plants"],
        "shop.tab.items":              ["de": "Gegenstände",         "en": "Items"],
        "Suchen...":                   ["de": "Suchen...",           "en": "Search..."],
        "Power-Ups":                   ["de": "Power-Ups",           "en": "Power-Ups"],
        "Dekorationen":                ["de": "Dekorationen",        "en": "Decorations"],
        "Alle":                        ["de": "Alle",                "en": "All"],
        "Kategorie":                   ["de": "Kategorie",           "en": "Category"],
        "shop.buy.confirm":            ["de": "Wirklich für %d Coins kaufen?",   "en": "Really buy for %d coins?"],
        "shop.buy.insufficient":       ["de": "Du brauchst noch %d Coins mehr",  "en": "You need %d more coins"],
        "shop.buy.success":            ["de": "Gekauft!",            "en": "Purchased!"],
        "shop.owned":                  ["de": "Bereits im Besitz",   "en": "Already owned"],
        "shop.purchases.count":        ["de": "Käufe im Shop",       "en": "Shop Purchases"],
        "shop.item.description":       ["de": "Beschreibung",        "en": "Description"],
        "shop.item.usage":             ["de": "Benutzung",          "en": "Usage"],
        "shop.your_balance":           ["de": "Dein Stand:",         "en": "Your Balance:"],
        "shop.already_owned":          ["de": "Bereits im Besitz",   "en": "Already Owned"],
        "shop.not_enough_coins":       ["de": "Zu wenig Coins",      "en": "Not Enough Coins"],
        "shop.need_more_coins":        ["de": "Du brauchst noch %d Coins mehr.", "en": "You need %d more coins."],
        "shop.trash_item_subtitle":    ["de": "Dekoration",          "en": "Decoration"],
        "shop.purchase_success.title": ["de": "Gekauft! 🎉",         "en": "Purchased! 🎉"],
        "shop.purchase_success.awesome":["de": "Super!",             "en": "Awesome!"],

        // MARK: Tags & Categories
        "Fitness":          ["de": "Fitness",          "en": "Fitness"],
        "Ernährung":        ["de": "Ernährung",        "en": "Nutrition"],
        "Ausdauer":         ["de": "Ausdauer",         "en": "Endurance"],
        "Lernen":           ["de": "Lernen",           "en": "Learning"],
        "Mental Health":    ["de": "Mental Health",    "en": "Mental Health"],
        "Schlaf":           ["de": "Schlaf",           "en": "Sleep"],
        "Hygiene":          ["de": "Hygiene",          "en": "Hygiene"],
        "Finanzen":         ["de": "Finanzen",         "en": "Finance"],
        "Soziales":         ["de": "Soziales",         "en": "Social"],
        "Kreativität":      ["de": "Kreativität",      "en": "Creativity"],
        "Achtsamkeit":      ["de": "Achtsamkeit",      "en": "Mindfulness"],
        "Produktivität":    ["de": "Produktivität",    "en": "Productivity"],
        "Suchtfreiheit":    ["de": "Suchtfreiheit",    "en": "Addiction-Free"],
        "Lifestyle":        ["de": "Lifestyle",        "en": "Lifestyle"],
        "Gewöhnlich":       ["de": "Gewöhnlich",       "en": "Common"],
        "Selten":           ["de": "Selten",           "en": "Rare"],
        "Episch":           ["de": "Episch",           "en": "Epic"],
        "Legendär":         ["de": "Legendär",         "en": "Legendary"],
        "DEKO":             ["de": "DEKO",             "en": "DECOR"],

        // MARK: Rarity
        "rarity.bronze":  ["de": "Bronze",  "en": "Bronze"],
        "rarity.silber":  ["de": "Silber",  "en": "Silver"],
        "rarity.gold":    ["de": "Gold",    "en": "Gold"],
        "rarity.diamant": ["de": "Diamant", "en": "Diamond"],

        // MARK: Streak
        "streak.days":     ["de": "%d Tage",             "en": "%d Days"],
        "streak.lost":     ["de": "Streak verloren",     "en": "Streak lost"],
        "streak.complete": ["de": "Alle Pflanzen gegossen!", "en": "All plants watered!"],

        // MARK: Profile
        "profile.title":                     ["de": "Profil",                                "en": "Profile"],
        "profile.coins":                     ["de": "Coins",                                 "en": "Coins"],
        "profile.plants":                    ["de": "Pflanzen",                              "en": "Plants"],
        "profile.streak":                    ["de": "Tage",                                  "en": "Days"],
        "profile.achievements":              ["de": "Erfolge",                               "en": "Achievements"],
        "profile.achievements.empty":        ["de": "Noch keine Erfolge freigeschaltet",     "en": "No achievements unlocked yet"],
        "profile.user.name":                 ["de": "Jannik Schill",                         "en": "Jannik Schill"],
        "profile.achievements.subtitle":     ["de": "Dein Trophäen-Schrank",                "en": "Your Trophy Cabinet"],
        "profile.achievements.unlocked":     ["de": "Erfolge freigeschaltet",               "en": "Achievements Unlocked"],
        "profile.achievements.locked_desc":  ["de": "Noch nicht freigeschaltet",            "en": "Not yet unlocked"],
        "profile.coins.available":           ["de": "Coins verfügbar",                       "en": "Coins Available"],
        "profile.coins.total":               ["de": "Gesamtstand",                           "en": "Total Balance"],
        "profile.coins.earned":              ["de": "Verdient (gesamt)",                     "en": "Earned (Total)"],
        "profile.coins.spent":               ["de": "Ausgegeben",                            "en": "Spent"],
        "profile.coins.how_to_earn":         ["de": "SO VERDIENST DU COINS",                "en": "HOW TO EARN COINS"],
        "profile.coins.tip.habit":           ["de": "Gewohnheit erledigen",                  "en": "Complete a habit"],
        "profile.coins.tip.streak":          ["de": "7-Tage Streak",                         "en": "7-Day Streak"],
        "profile.coins.tip.levelup":         ["de": "Level Up",                              "en": "Level Up"],
        "profile.coins.tip.watering":        ["de": "Alle Pflanzen gießen",                  "en": "Water all plants"],
        "profile.plants.subtitle":           ["de": "Pflanzen in deinem Garten",             "en": "Plants in your garden"],
        "profile.plants.list":               ["de": "MEINE PFLANZEN",                        "en": "MY PLANTS"],
        "profile.xp.earned":                 ["de": "Verdiente XP",                          "en": "XP Earned"],
        "profile.xp.max":                    ["de": "Meiste XP",                             "en": "Most XP"],
        "profile.transactions.empty":        ["de": "Noch keine Transaktionen",              "en": "No transactions yet"],

        // MARK: Common
        "common.details": ["de": "DETAILS",  "en": "DETAILS"],
        "common.history": ["de": "VERLAUF",  "en": "HISTORY"],
        "common.total":   ["de": "Gesamt",   "en": "Total"],
        "common.active":  ["de": "Aktiv",    "en": "Active"],
        "common.of":      ["de": "von",      "en": "of"],
        "common.done":    ["de": "FERTIG",   "en": "DONE"],

        // MARK: Level Up & Weather
        "level_up.title":    ["de": "STUFEN-AUFSTIEG! 🎉", "en": "LEVEL UP! 🎉"],
        "level_up.subtitle": ["de": "Dein Garten ist jetzt", "en": "Your garden is now"],
        "weather.new_event": ["de": "Neues Wetter-Event!",   "en": "New Weather Event!"],
        "weather.today_is":  ["de": "Heute gilt",            "en": "Today is"],

        // Weather Event Titles
        "weather.normal.title":  ["de": "Ruhiger Tag",        "en": "Calm Day"],
        "weather.duerre.title":  ["de": "Dürre-Alarm!",       "en": "Drought Alert!"],
        "weather.schnee.title":  ["de": "Frostwarnung",       "en": "Frost Warning"],
        "weather.sturm.title":   ["de": "Sturm zieht auf",    "en": "Storm Approaching"],
        "weather.perfekt.title": ["de": "Perfektes Wetter!",  "en": "Perfect Weather!"],

        // Weather Event Subtitles
        "weather.normal.subtitle":  ["de": "Alles wächst nach Plan",       "en": "Everything grows as planned"],
        "weather.duerre.subtitle":  ["de": "Doppeltes Gießen nötig!",      "en": "Double watering required!"],
        "weather.schnee.subtitle":  ["de": "Nur 50% Belohnung heute",      "en": "Only 50% reward today"],
        "weather.sturm.subtitle":   ["de": "Schwache Pflanzen in Gefahr!", "en": "Weak plants in danger!"],
        "weather.perfekt.subtitle": ["de": "Doppelte Belohnung heute!",    "en": "Double reward today!"],

        // MARK: Settings
        "settings.title":                   ["de": "Einstellungen",               "en": "Settings"],
        "settings.done":                    ["de": "Fertig",                       "en": "Done"],
        "settings.section.personalization": ["de": "Personalisierung",            "en": "Personalization"],
        "settings.section.general":         ["de": "Allgemein",                   "en": "General"],
        "settings.section.privacy":         ["de": "Datenschutz & Sicherheit",    "en": "Privacy & Security"],
        "settings.section.support":         ["de": "Unterstützung",               "en": "Support"],
        "settings.language":                ["de": "Sprache",                     "en": "Language"],
        "settings.language.de":             ["de": "Deutsch",                     "en": "German"],
        "settings.language.en":             ["de": "Englisch",                    "en": "English"],
        "settings.audio":                   ["de": "Audio & Sounds",              "en": "Audio & Sounds"],
        "settings.haptic":                  ["de": "Haptik Feedback",             "en": "Haptic Feedback"],
        "settings.notifications":           ["de": "Benachrichtigungen",          "en": "Notifications"],
        "settings.privacy_settings":        ["de": "Datenschutz-Einstellungen",   "en": "Privacy Settings"],
        "settings.terms":                   ["de": "Nutzungsbedingungen",         "en": "Terms of Service"],
        "settings.export":                  ["de": "Daten exportieren",           "en": "Export Data"],
        "settings.import":                  ["de": "Daten importieren",           "en": "Import Data"],
        "settings.restore":                 ["de": "Käufe wiederherstellen",      "en": "Restore Purchases"],
        "settings.contact":                 ["de": "Support kontaktieren",        "en": "Contact Support"],
        "settings.share":                   ["de": "App weiterempfehlen",         "en": "Recommend App"],
        "settings.delete_account":          ["de": "ACCOUNT LÖSCHEN",            "en": "DELETE ACCOUNT"],
        "settings.delete_warning":          ["de": "Diese Aktion kann nicht rückgängig gemacht werden.", "en": "This action cannot be undone."],
        "settings.understood":              ["de": "Verstanden",                  "en": "Understood"],
        "settings.action.irreversible":     ["de": "Diese Aktion kann nicht rückgängig gemacht werden.", "en": "This action cannot be undone."],
        "settings.export.desc":             ["de": "Möchten Sie alle Ihre Daten exportieren? Sie erhalten eine Datei mit allen Ihren Pflanzen und Fortschritten.", "en": "Do you want to export all your data? You will receive a file with all your plants and progress."],
        "settings.export.action":           ["de": "Export starten",              "en": "Start Export"],
        "settings.import.desc":             ["de": "Möchten Sie Daten importieren? Dies überschreibt Ihre aktuellen Fortschritte.", "en": "Do you want to import data? This will overwrite your current progress."],
        "settings.import.action":           ["de": "Import starten",              "en": "Start Import"],
        "settings.restore.desc":            ["de": "Haben Sie bereits Käufe getätigt? Hier können Sie diese auf diesem Gerät wiederherstellen.", "en": "Have you already made purchases? You can restore them on this device here."],
        "settings.restore.action":          ["de": "Wiederherstellen",            "en": "Restore"],
        "settings.contact.desc":            ["de": "Haben Sie Fragen oder Probleme? Unser Support-Team hilft Ihnen gerne weiter.", "en": "Do you have questions or problems? Our support team will be happy to help you."],
        "settings.contact.action":          ["de": "Support öffnen",              "en": "Open Support"],
        "settings.share.desc":              ["de": "Gefällt Ihnen die Garten-Simulation? Teilen Sie sie mit Ihren Freunden!", "en": "Do you like the Garden Simulation? Share it with your friends!"],
        "settings.share.action":            ["de": "App teilen",                  "en": "Share App"],
        "settings.privacy.desc":            ["de": "Hier findest du alle Informationen zu den Datenschutzbestimmungen.", "en": "Here you can find all information about the privacy policy."],
        "settings.terms.desc":              ["de": "Hier findest du alle Informationen zu den Nutzungsbedingungen.", "en": "Here you can find all information about the terms of service."],

        // MARK: Achievement Categories
        "category.streak":   ["de": "Streak",    "en": "Streak"],
        "category.daytime":  ["de": "Tageszeit", "en": "Time of Day"],
        "category.plants":   ["de": "Pflanzen",  "en": "Plants"],
        "category.coins":    ["de": "Coins",     "en": "Coins"],

        // MARK: Achievements – Streak
        "achievement.streak3.title":   ["de": "Erste Schritte",    "en": "First Steps"],
        "achievement.streak3.desc":    ["de": "3 Tage Streak",     "en": "3 Day Streak"],
        "achievement.streak7.title":   ["de": "Eine Woche",        "en": "One Week"],
        "achievement.streak7.desc":    ["de": "7 Tage Streak",     "en": "7 Day Streak"],
        "achievement.streak30.title":  ["de": "Monats-Krieger",    "en": "Month Warrior"],
        "achievement.streak30.desc":   ["de": "30 Tage Streak",    "en": "30 Day Streak"],
        "achievement.streak100.title": ["de": "Legende",           "en": "Legend"],
        "achievement.streak100.desc":  ["de": "100 Tage Streak",   "en": "100 Day Streak"],

        // MARK: Achievements – Coins
        "achievement.coin100.title":   ["de": "Erstes Taschengeld", "en": "First Pocket Money"],
        "achievement.coin100.desc":    ["de": "100 Coins gesammelt","en": "Collected 100 Coins"],
        "achievement.coin1000.title":  ["de": "Sparfuchs",          "en": "Money Saver"],
        "achievement.coin1000.desc":   ["de": "1.000 Coins gesammelt", "en": "Collected 1,000 Coins"],
        "achievement.coin5000.title":  ["de": "Reicher Gärtner",   "en": "Rich Gardener"],
        "achievement.coin5000.desc":   ["de": "5.000 Coins gesammelt", "en": "Collected 5,000 Coins"],
        "achievement.coin10000.title": ["de": "Millionär",          "en": "Millionaire"],
        "achievement.coin10000.desc":  ["de": "10.000 Coins gesammelt", "en": "Collected 10,000 Coins"],

        // MARK: Achievements – Plants
        "achievement.pfl1.title":  ["de": "Erster Setzling",  "en": "First Seedling"],
        "achievement.pfl1.desc":   ["de": "1 Pflanze im Garten", "en": "1 plant in the garden"],
        "achievement.pfl5.title":  ["de": "Kleiner Garten",   "en": "Small Garden"],
        "achievement.pfl5.desc":   ["de": "5 Pflanzen im Garten", "en": "5 plants in the garden"],
        "achievement.pfl10.title": ["de": "Grüner Daumen",    "en": "Green Thumb"],
        "achievement.pfl10.desc":  ["de": "10 Pflanzen im Garten", "en": "10 plants in the garden"],
        "achievement.pfl25.title": ["de": "Meister-Gärtner", "en": "Master Gardener"],
        "achievement.pfl25.desc":  ["de": "25 Pflanzen im Garten", "en": "25 plants in the garden"],

        // MARK: Achievements – Time of Day
        "achievement.morgen5.title":  ["de": "Frühaufsteher",      "en": "Early Bird"],
        "achievement.morgen5.desc":   ["de": "5× vor 9 Uhr erledigt", "en": "Done 5× before 9 AM"],
        "achievement.morgen30.title": ["de": "Morgen-Meister",     "en": "Morning Master"],
        "achievement.morgen30.desc":  ["de": "30× vor 9 Uhr erledigt", "en": "Done 30× before 9 AM"],
        "achievement.abend5.title":   ["de": "Nacht-Eule",         "en": "Night Owl"],
        "achievement.abend5.desc":    ["de": "5× nach 20 Uhr erledigt", "en": "Done 5× after 8 PM"],
        "achievement.abend30.title":  ["de": "Mitternachts-Krieger", "en": "Midnight Warrior"],
        "achievement.abend30.desc":   ["de": "30× nach 20 Uhr erledigt", "en": "Done 30× after 8 PM"],

        // MARK: Plants
        "plant.bambus.name":               ["de": "Bambus",           "en": "Bamboo"],
        "plant.bambus.symbolism":          ["de": "Wächst schnell, extrem stabil und schwer zu brechen", "en": "Grows fast, extremely stable and hard to break"],
        "plant.apfelbaum.name":            ["de": "Apfelbaum",        "en": "Apple Tree"],
        "plant.apfelbaum.symbolism":       ["de": "Level 1 = Kern, Level 10 = voller Baum. Klassisch gesund", "en": "Level 1 = seed, Level 10 = full tree. Classic health"],
        "plant.wildgras.name":             ["de": "Wildgras",         "en": "Wild Grass"],
        "plant.wildgras.symbolism":        ["de": "Zäh, regeneriert sich blitzschnell, bedeckt das Spielfeld", "en": "Tough, regenerates lightning fast, covers the field"],
        "plant.eiche.name":                ["de": "Eiche",            "en": "Oak"],
        "plant.eiche.symbolism":           ["de": "Wächst langsam, wird über Jahrzehnte massiv und weise", "en": "Grows slowly, becomes massive and wise over decades"],
        "plant.lotus.name":                ["de": "Lotus",            "en": "Lotus"],
        "plant.lotus.symbolism":           ["de": "Blüht im Schlamm – Ruhe trotz Stress", "en": "Blooms in mud – peace despite stress"],
        "plant.sonnenblume.name":          ["de": "Sonnenblume",      "en": "Sunflower"],
        "plant.sonnenblume.symbolism":     ["de": "Dreht sich immer zur Sonne – Frühaufsteher-Energie", "en": "Always turns to the sun – Early bird energy"],
        "plant.kaktus.name":               ["de": "Kaktus",           "en": "Cactus"],
        "plant.kaktus.symbolism":          ["de": "Überlebt extremste Bedingungen – Kalt duschen", "en": "Survives extreme conditions – Cold showers"],
        "plant.weinrebe.name":             ["de": "Weinrebe",         "en": "Vine"],
        "plant.weinrebe.symbolism":        ["de": "Je länger nüchtern, desto reicher die Ernte", "en": "The longer sober, the richer the harvest"],
        "plant.kirschbaum.name":           ["de": "Kirschbaum",       "en": "Cherry Tree"],
        "plant.kirschbaum.symbolism":      ["de": "Blüht nur, wenn man sich gut um ihn kümmert – Selfcare", "en": "Blooms only with good care – Selfcare"],
        "plant.palme.name":                ["de": "Palme",            "en": "Palm Tree"],
        "plant.palme.symbolism":           ["de": "Steht in der Wärme, braucht weite Horizonte – Abenteuer", "en": "Stands in the heat, needs wide horizons – Adventure"],
        "plant.minzpflanze.name":          ["de": "Minzpflanze",      "en": "Mint Plant"],
        "plant.minzpflanze.symbolism":     ["de": "Frisch, klar, täglich – Zähneputzen & Hygiene", "en": "Fresh, clear, daily – Toothbrushing & Hygiene"],
        "plant.rosmarin.name":             ["de": "Rosmarin",         "en": "Rosemary"],
        "plant.rosmarin.symbolism":        ["de": "Würzt das Leben, braucht tägliche Pflege – Meal Prep", "en": "Spices up life, needs daily care – Meal Prep"],
        "plant.mandelbaum.name":           ["de": "Mandelbaum",       "en": "Almond Tree"],
        "plant.mandelbaum.symbolism":      ["de": "Investition zahlt sich erst später aus – Sparen", "en": "Investment pays off later – Saving"],
        "plant.bambus_schilf.name":        ["de": "Bambus-Schilf",    "en": "Bamboo Reed"],
        "plant.bambus_schilf.symbolism":   ["de": "Flexibel aber unzerbrechlich – Journaling", "en": "Flexible but unbreakable – Journaling"],
        "plant.lavendel.name":             ["de": "Lavendel",         "en": "Lavender"],
        "plant.lavendel.symbolism":        ["de": "Beruhigt und entspannt den Geist – besserer Schlaf", "en": "Calms and relaxes the mind – better sleep"],
        "plant.efeu.name":                 ["de": "Efeu",             "en": "Ivy"],
        "plant.efeu.symbolism":            ["de": "Breitet sich langsam aber stetig aus – tägliches Dehnen", "en": "Spreads slowly but steadily – daily stretching"],
        "plant.aloe_vera.name":            ["de": "Aloe Vera",        "en": "Aloe Vera"],
        "plant.aloe_vera.symbolism":       ["de": "Heilt und regeneriert still im Hintergrund – weniger Handy", "en": "Heals and regenerates silently – less phone time"],
        "plant.erdbeerpflanze.name":       ["de": "Erdbeerpflanze",   "en": "Strawberry Plant"],
        "plant.erdbeerpflanze.symbolism":  ["de": "Kleine Früchte, große Belohnung – Obst & Gemüse essen", "en": "Small fruits, big reward – eating fruit & veg"],
        "plant.zitronenbaum.name":         ["de": "Zitronenbaum",     "en": "Lemon Tree"],
        "plant.zitronenbaum.symbolism":    ["de": "Sauer macht stark – Vitamin C & Immunsystem", "en": "Sour makes power – Vitamin C & Immune system"],
        "plant.weizenfeld.name":           ["de": "Weizenfeld",       "en": "Wheat Field"],
        "plant.weizenfeld.symbolism":      ["de": "Viele kleine Ähren = große Ernte – Deep Work", "en": "Many small ears = big harvest – Deep Work"],
        "plant.orchidee.name":             ["de": "Orchidee",         "en": "Orchid"],
        "plant.orchidee.symbolism":        ["de": "Selten, fragil, aber wunderschön wenn gepflegt – Kunst", "en": "Rare, fragile, but beautiful when cared for – Art"],
        "plant.pilzkolonie.name":          ["de": "Pilzkolonie",      "en": "Mushroom Colony"],
        "plant.pilzkolonie.symbolism":     ["de": "Wächst im Verborgenen, verbindet alles – Networking", "en": "Grows in hiding, connects everything – Networking"],
        "plant.mangrove.name":             ["de": "Mangrove",         "en": "Mangrove"],
        "plant.mangrove.symbolism":        ["de": "Hält auch in Stürmen stand – Resilienz & Stressabbau", "en": "Stands firm even in storms – Resilience & Stress relief"],
        "plant.klee.name":                 ["de": "Klee",             "en": "Clover"],
        "plant.klee.symbolism":            ["de": "Kleines Glück, täglich gefunden – Dankbarkeit", "en": "Small luck, found daily – Gratitude"],
        "plant.farn.name":                 ["de": "Farn",             "en": "Fern"],
        "plant.farn.symbolism":            ["de": "Braucht kein Licht von Bildschirmen – Digital Detox", "en": "Needs no light from screens – Digital Detox"],
        "plant.chrysantheme.name":         ["de": "Chrysantheme",     "en": "Chrysanthemum"],
        "plant.chrysantheme.symbolism":    ["de": "Ordnung = Blüte – Sauberkeit & Aufräumen", "en": "Order = Bloom – Cleanliness & Tidying"],
        "plant.walnussbaum.name":          ["de": "Walnussbaum",      "en": "Walnut Tree"],
        "plant.walnussbaum.symbolism":     ["de": "Harte Schale, wertvoller Kern – Weiterbildung & Kurse", "en": "Hard shell, valuable core – Further education & Courses"],
        "plant.pfirsichbaum.name":         ["de": "Pfirsichbaum",     "en": "Peach Tree"],
        "plant.pfirsichbaum.symbolism":    ["de": "Braucht sanfte Pflege, keine Gewalt – Stressreduktion", "en": "Needs gentle care, no violence – Stress reduction"],
        "plant.brennnessel.name":          ["de": "Brennnessel",      "en": "Stinging Nettle"],
        "plant.brennnessel.symbolism":     ["de": "Schmerzt kurz, macht unkaputtbar – Kaltdusche + Gym Kombo", "en": "Stings briefly, makes unbreakable – Cold shower + gym combo"],
        "plant.bonsai.name":               ["de": "Bonsai",           "en": "Bonsai"],
        "plant.bonsai.symbolism":          ["de": "Braucht Jahre – wird ein Meisterwerk – Geduld & Langzeitprojekte", "en": "Takes years – becomes a masterpiece – Patience & long-term projects"],
        "plant.seerose.name":              ["de": "Seerose",          "en": "Water Lily"],
        "plant.seerose.symbolism":         ["de": "Wächst im Wasser, ruhig und stark – Schwimmen", "en": "Grows in water, calm and strong – Swimming"],
        "plant.zuckerrohr.name":           ["de": "Zuckerrohr",       "en": "Sugar Cane"],
        "plant.zuckerrohr.symbolism":      ["de": "Kein Zucker = das Feld bleibt sauber – Zuckerfrei + Sport", "en": "No sugar = the field stays clean – Sugar-free + Sports"],
        "plant.basilikum.name":            ["de": "Basilikum",        "en": "Basil"],
        "plant.basilikum.symbolism":       ["de": "Klein aber intensiv im Geschmack – Bewusstes Essen", "en": "Small but intense in flavor – Mindful eating"],
        "plant.kakaobaum.name":            ["de": "Kakaobaum",        "en": "Cocoa Tree"],
        "plant.kakaobaum.symbolism":       ["de": "Süß nur nach harter Arbeit – Belohnung verdienen", "en": "Sweet only after hard work – Earn the reward"],
        "plant.feigenbaum.name":           ["de": "Feigenbaum",       "en": "Fig Tree"],
        "plant.feigenbaum.symbolism":      ["de": "Braucht Pausen um zu tragen – Intervallfasten", "en": "Needs breaks to bear fruit – Intermittent fasting"],
        "plant.korallenbusch.name":        ["de": "Korallenbusch",    "en": "Coral Bush"],
        "plant.korallenbusch.symbolism":   ["de": "Wächst nur im richtigen Ökosystem – Freundschaften pflegen", "en": "Grows only in the right ecosystem – Nurturing friendships"],
        "plant.eukalyptus.name":           ["de": "Eukalyptus",       "en": "Eucalyptus"],
        "plant.eukalyptus.symbolism":      ["de": "Reinigt die Luft von innen – Atemübungen & Breathwork", "en": "Cleans the air from within – Breathing exercises & Breathwork"],
        "plant.thymian.name":              ["de": "Thymian",          "en": "Thyme"],
        "plant.thymian.symbolism":         ["de": "Klein, unscheinbar, aber immer da – Konsequenz & Routine", "en": "Small, inconspicuous, but always there – Consistency & Routine"],
        "plant.ginkgo.name":               ["de": "Ginkgo",           "en": "Ginkgo"],
        "plant.ginkgo.symbolism":          ["de": "Ältester Baum der Welt – unvergesslich – Gedächtnisübungen", "en": "Oldest tree in the world – unforgettable – Memory exercises"],
        "plant.mammutbaum.name":           ["de": "Mammutbaum",       "en": "Sequoia"],
        "plant.mammutbaum.symbolism":      ["de": "Größter Baum der Welt – braucht alles – Jahresprojekt & Big Goal", "en": "Largest tree in the world – needs everything – Year project & Big Goal"],
        "plant.passionsblume.name":        ["de": "Passionsblume",    "en": "Passion Flower"],
        "plant.passionsblume.symbolism":   ["de": "Blüht bei innerer Beherrschung – Selbstdisziplin", "en": "Blooms with inner control – Self-discipline"],
        "plant.ingwerpflanze.name":        ["de": "Ingwerpflanze",    "en": "Ginger Plant"],
        "plant.ingwerpflanze.symbolism":   ["de": "Scharfe Alternative, natürliche Energie – Kein Koffein", "en": "Sharp alternative, natural energy – No caffeine"],
        "plant.teestrauch.name":           ["de": "Teestrauch",       "en": "Tea Shrub"],
        "plant.teestrauch.symbolism":      ["de": "Sanfter, nachhaltiger Wachstum – Weniger Kaffee", "en": "Gentle, sustainable growth – Less coffee"],
        "plant.olivenbaum.name":           ["de": "Olivenbaum",       "en": "Olive Tree"],
        "plant.olivenbaum.symbolism":      ["de": "Lebt 1000 Jahre – Beständigkeit pur – Mediterraner Lifestyle", "en": "Lives 1,000 years – pure persistence – Mediterranean lifestyle"],

        // MARK: - Game Database - Decorations (formerly Trash)
        "trash.ultra_konsole.name":         ["de": "Gartenbank",          "en": "Garden Bench"],
        "trash.ultra_konsole.desc":         ["de": "Ein gemütlicher Ort zum Verweilen.", "en": "A cozy place to relax."],
        "trash.fast_food_abo.name":          ["de": "Brunnen",             "en": "Fountain"],
        "trash.fast_food_abo.desc":          ["de": "Beruhigendes Geplätscher für deinen Garten. (+1 Coin)", "en": "Calming water sounds for your garden. (+1 Coin)"],
        "trash.endlos_scroll_tv.name":       ["de": "Vogelhäuschen",       "en": "Birdhouse"],
        "trash.endlos_scroll_tv.desc":       ["de": "Zieht zwitschernde Freunde an.", "en": "Attracts chirping friends."],
        "trash.luxus_auto.name":             ["de": "Laterne",             "en": "Lantern"],
        "trash.luxus_auto.desc":             ["de": "Spendet sanftes Licht am Abend.", "en": "Provides soft light in the evening."],
        "trash.party_pass.name":             ["de": "Trittstein-Pfad",      "en": "Stepping Stone Path"],
        "trash.party_pass.desc":             ["de": "Ein schöner Weg durchs Grüne.", "en": "A beautiful path through the greenery."],
        "trash.energy_drink_kiste.name":     ["de": "Gartenzwerg",         "en": "Garden Gnome"],
        "trash.energy_drink_kiste.desc":     ["de": "Ein klassischer Wächter.", "en": "A classic garden protector."],
        "trash.zigaretten_automat.name":     ["de": "Sonnenschirm",        "en": "Sun Umbrella"],
        "trash.zigaretten_automat.desc":     ["de": "Spendet Schatten an heißen Tagen.", "en": "Provides shade on hot days."],
        "trash.online_shopping_app.name":    ["de": "Seerosenteich",       "en": "Lily Pond"],
        "trash.online_shopping_app.desc":    ["de": "Ein Biotop für Wasserfreunde. (+2 Coins)", "en": "A biotope for water lovers. (+2 Coins)"],
        "trash.junk_mail_abo.name":          ["de": "Vogelbad",            "en": "Bird Bath"],
        "trash.junk_mail_abo.desc":          ["de": "Erfrischung für die Vögel.", "en": "A quick refresh for the birds."],
        "trash.nacht_snack_box.name":        ["de": "Holzzaun",            "en": "Wooden Fence"],
        "trash.nacht_snack_box.desc":        ["de": "Grenzt deinen Garten sicher ab.", "en": "Secures your garden boundaries."],
        "trash.alkohol_flatrate.name":       ["de": "Steinstatue",         "en": "Stone Statue"],
        "trash.alkohol_flatrate.desc":       ["de": "Ein Hauch von Kunst und Zeitlosigkeit.", "en": "A touch of art and timelessness."],
        "trash.doomscrolling_handy.name":    ["de": "Windrad",             "en": "Windmill"],
        "trash.doomscrolling_handy.desc":    ["de": "Dreht sich fröhlich im Wind.", "en": "Spins happily in the wind."],
        "trash.binge_streaming.name":        ["de": "Hängematte",          "en": "Hammock"],
        "trash.binge_streaming.desc":        ["de": "Perfekt für ein kleines Schläfchen.", "en": "Perfect for a little nap."],
        "trash.fastfood_lieferdienst.name":  ["de": "Gartenfackel",        "en": "Garden Torch"],
        "trash.fastfood_lieferdienst.desc":  ["de": "Feurige Beleuchtung für die Nacht.", "en": "Fiery lighting for the night."],
        "trash.lootbox_zockerabo.name":      ["de": "Blumenkübel",         "en": "Flower Pot"],
        "trash.lootbox_zockerabo.desc":      ["de": "Zusätzlicher Platz für wilde Blumen.", "en": "Extra space for wild flowers."],
        "trash.luxus_uhr.name":              ["de": "Bienenhaus",          "en": "Bee House"],
        "trash.luxus_uhr.desc":              ["de": "Summende Helfer für die Bestäubung. (+1 Coin)", "en": "Buzzing helpers for pollination. (+1 Coin)"],
        "trash.couch_abo.name":              ["de": "Igelhaus",            "en": "Hedgehog House"],
        "trash.couch_abo.desc":              ["de": "Ein sicheres Quartier für Igel.", "en": "A safe quarter for hedgehogs."],
        "trash.doener_dauerkarte.name":      ["de": "Kiesweg",             "en": "Gravel Path"],
        "trash.doener_dauerkarte.desc":      ["de": "Knirscht so schön beim Drüberlaufen.", "en": "Crunches nicely when walking over it."],
        "trash.negativitaets_feed.name":     ["de": "Brücke",              "en": "Bridge"],
        "trash.negativitaets_feed.desc":     ["de": "Verbindet verschiedene Gartenbereiche.", "en": "Connects different garden areas."],
        "trash.schlaf_killer_koffein.name":  ["de": "Gartenhütte",         "en": "Garden Shed"],
        "trash.schlaf_killer_koffein.desc":  ["de": "Viel Platz für alle deine Werkzeuge.", "en": "Plenty of space for all your tools."],

        // MARK: Power-Ups
        "item.frostschutz_schild.name":        ["de": "Frostschutz-Schild",  "en": "Frost Protection Shield"],
        "item.frostschutz_schild.description": ["de": "24h Schutz vor dem Schnee-Event.", "en": "24h protection from snow events."],
        "item.wunder_wasser.name":             ["de": "Wunder-Wasser",       "en": "Wonder Water"],
        "item.wunder_wasser.description":      ["de": "Rettet eine vertrocknete Pflanze sofort.", "en": "Rescues a dried plant immediately."],
        "item.sturmfeste_glocke.name":         ["de": "Sturmfeste Glocke",   "en": "Stormproof Bell"],
        "item.sturmfeste_glocke.description":  ["de": "Eine Pflanze übersteht den nächsten Sturm ohne Level-Down.", "en": "One plant survives the next storm without level-down."],
        "item.duenger_blitz.name":             ["de": "Dünger-Blitz",        "en": "Fertilizer Blitz"],
        "item.duenger_blitz.description":      ["de": "Verdoppelt XP für die nächsten 3 Erledigungen.", "en": "Doubles XP for the next 3 completions."],
        "item.unkraut_bot.name":               ["de": "Unkraut-Bot",         "en": "Weed Bot"],
        "item.unkraut_bot.description":        ["de": "3 Tage automatische Unkraut-Entfernung.", "en": "3 days automatic weed removal."],
        "item.sonnenspiegel.name":             ["de": "Sonnenspiegel",       "en": "Sun Mirror"],
        "item.sonnenspiegel.description":      ["de": "Negiert den Abgas-Nebel für 48 Stunden.", "en": "Negates exhaust smog for 48 hours."],
        "item.zeitkapsel.name":                ["de": "Zeitkapsel",          "en": "Time Capsule"],
        "item.zeitkapsel.description":         ["de": "Friert eine Pflanze ein – kein Verfall für 3 Tage.", "en": "Freezes a plant – no decay for 3 days."],
        "item.regenmacher.name":               ["de": "Regenmacher",         "en": "Rain Maker"],
        "item.regenmacher.description":        ["de": "Bewässert alle Pflanzen gleichzeitig gratis.", "en": "Waters all plants at once for free."],
        "item.goldene_giesskanne.name":        ["de": "Goldene Gießkanne",  "en": "Golden Watering Can"],
        "item.goldene_giesskanne.description": ["de": "+50% Wachstum für eine ganze Woche.", "en": "+50% growth for a full week."],
        "item.schaedlingsschutz.name":         ["de": "Schädlingsschutz",   "en": "Pest Protection"],
        "item.schaedlingsschutz.description":  ["de": "Blockiert alle Parasiten & Käfer-Effekte für 5 Tage.", "en": "Blocks all parasites & bug effects for 5 days."],
        "item.nebel_ventilator.name":          ["de": "Nebel-Ventilator",   "en": "Mist Fan"],
        "item.nebel_ventilator.description":   ["de": "Entfernt Rauch-Smog & Abgas-Nebel sofort.", "en": "Removes smoke smog & exhaust fog immediately."],
        "item.kompost_boost.name":             ["de": "Kompost-Boost",      "en": "Compost Boost"],
        "item.kompost_boost.description":      ["de": "Wandelt 1 Müll-Item in +20 XP um.", "en": "Converts 1 trash item into +20 XP."],
        "item.diamant_erde.name":              ["de": "Diamant-Erde",       "en": "Diamond Soil"],
        "item.diamant_erde.description":       ["de": "Permanentes +10% XP für eine Pflanze. Für immer.", "en": "Permanent +10% XP for one plant. Forever."],
        "item.tier_freund.name":               ["de": "Tier-Freund",        "en": "Animal Friend"],
        "item.tier_freund.description":        ["de": "Bestäubt 3 Pflanzen mit einem Mini-Level-Boost.", "en": "Pollinates 3 plants with a mini level boost."],
        "item.regenbogen_event.name":          ["de": "Regenbogen-Event",   "en": "Rainbow Event"],
        "item.regenbogen_event.description":   ["de": "Alle Pflanzen wachsen 24h doppelt so schnell.", "en": "All plants grow twice as fast for 24h."],

        // MARK: Power-Up Usage Instructions
        "item.frostschutz_schild.usage":       ["de": "Wird sofort aktiv und schützt deinen gesamten Garten.", "en": "Becomes active immediately and protects your entire garden."],
        "item.wunder_wasser.usage":            ["de": "Tippe auf eine vertrocknete Pflanze, um sie zu retten.", "en": "Tap on a dried plant to rescue it."],
        "item.sturmfeste_glocke.usage":        ["de": "Tippe auf die Pflanze, die du schützen möchtest.", "en": "Tap on the plant you want to protect."],
        "item.duenger_blitz.usage":             ["de": "Wird sofort aktiv und verdoppelt deine nächsten XP-Gewinne.", "en": "Becomes active immediately and doubles your next XP gains."],
        "item.unkraut_bot.usage":               ["de": "Wird sofort aktiv und entfernt automatisch alles Unkraut.", "en": "Becomes active immediately and automatically removes all weeds."],
        "item.sonnenspiegel.usage":            ["de": "Wird sofort aktiv und sorgt für klaren Himmel.", "en": "Becomes active immediately and ensures clear skies."],
        "item.zeitkapsel.usage":               ["de": "Wird sofort aktiv und stoppt den Verfall aller Pflanzen.", "en": "Becomes active immediately and stops decay for all plants."],
        "item.regenmacher.usage":              ["de": "Wird sofort aktiv und gießt alle Pflanzen im Garten.", "en": "Becomes active immediately and waters all plants in the garden."],
        "item.goldene_giesskanne.usage":       ["de": "Wird sofort aktiv und erhöht das Wachstum dauerhaft.", "en": "Becomes active immediately and increases growth permanently."],
        "item.schaedlingsschutz.usage":        ["de": "Wird sofort aktiv und hält alle Schädlinge fern.", "en": "Becomes active immediately and keeps all pests away."],
        "item.nebel_ventilator.usage":         ["de": "Benutze ihn, wenn der Garten von Smog bedeckt ist.", "en": "Use it when the garden is covered in smog."],
        "item.kompost_boost.usage":            ["de": "Tippe auf ein Müll-Item, um es in XP zu verwandeln.", "en": "Tap on a trash item to convert it into XP."],
        "item.diamant_erde.usage":             ["de": "Wird sofort aktiv und verbessert die Bodenqualität.", "en": "Becomes active immediately and improves soil quality."],
        "item.tier_freund.usage":              ["de": "Wird sofort aktiv und ruft kleine Helfer in den Garten.", "en": "Becomes active immediately and calls little helpers to the garden."],
        "item.regenbogen_event.usage":         ["de": "Wird sofort aktiv und lässt alles bunt erstrahlen.", "en": "Becomes active immediately and makes everything shine colorfully."],
        "decoration.category.moebel":      ["de": "Möbel",       "en": "Furniture"],
        "decoration.category.wasser":      ["de": "Wasser",      "en": "Water"],
        "decoration.category.tiere":       ["de": "Tiere",       "en": "Animals"],
        "decoration.category.pfade":       ["de": "Pfade",       "en": "Paths"],
        "decoration.category.beleuchtung": ["de": "Beleuchtung", "en": "Lighting"],

        "achievement.deko1.title": ["de": "Gärtner-Designer", "en": "Garden Designer"],
        "achievement.deko1.desc":  ["de": "Erste Dekoration gekauft", "en": "Bought first decoration"],
        "achievement.deko5.title": ["de": "Vollständiger Garten", "en": "Complete Garden"],
        "achievement.deko5.desc":  ["de": "5 Dekorationen gleichzeitig platziert", "en": "5 decorations placed at once"],

        // MARK: Plant Detail Sheet
        "plant.detail.note":               ["de": "Notiz",                          "en": "Note"],
        "plant.detail.note.placeholder":   ["de": "Schreibe eine Notiz...",         "en": "Write a note..."],
        "plant.detail.note.save":          ["de": "Speichern",                      "en": "Save"],
        "plant.detail.timer":              ["de": "Timer",                          "en": "Timer"],
        "plant.detail.timer.set":          ["de": "Erinnerung setzen",              "en": "Set Reminder"],
        "plant.detail.timer.active":       ["de": "Erinnerung aktiv",               "en": "Reminder active"],
        "plant.detail.timer.delete":       ["de": "Timer löschen",                  "en": "Delete Timer"],
        "plant.detail.sell":               ["de": "Pflanze verkaufen",              "en": "Sell Plant"],
        "plant.detail.sell.confirm":       ["de": "Möchtest du diese Pflanze wirklich verkaufen?", "en": "Do you really want to sell this plant?"],
        "plant.detail.sell.action":        ["de": "Verkaufen",                      "en": "Sell"],
        "plant.detail.xp":                 ["de": "XP",                             "en": "XP"],
        "plant.detail.streak":             ["de": "Streak",                         "en": "Streak"],

        // MARK: Reset App Data
        "settings.section.danger":         ["de": "GEFAHRENZONE",                   "en": "DANGER ZONE"],
        "settings.reset.title":            ["de": "Alle Daten löschen",             "en": "Delete All Data"],
        "settings.reset.alert.title":      ["de": "App zurücksetzen?",              "en": "Reset App?"],
        "settings.reset.alert.message":     ["de": "Diese Aktion löscht alle deine Pflanzen, Coins und Fortschritte. Das kann nicht rückgängig gemacht werden.", "en": "This action will delete all your plants, coins, and progress. This cannot be undone."],
        "settings.reset.confirm":          ["de": "Alles löschen",                  "en": "Delete Everything"],

        // MARK: Daily Spin
        "dailyspin.title":                 ["de": "Daily Spin",                                      "en": "Daily Spin"],
        "dailyspin.subtitle":              ["de": "Drehe das Rad, um in den Tag zu starten!",        "en": "Spin the wheel to start your day!"],
        "dailyspin.button.spin":           ["de": "RAD DREHEN",                                      "en": "SPIN THE WHEEL"],
        "dailyspin.button.continue":       ["de": "Weiter",                                          "en": "Continue"],
        "dailyspin.weed.danger":           ["de": "Unkraut-Gefahr: %d%%",                            "en": "Weed Risk: %d%%"],
        "dailyspin.result.safe.title":     ["de": "Alles gut!",                                      "en": "All Clear!"],
        "dailyspin.result.safe.subtitle":  ["de": "Dein Garten ist sicher.",                         "en": "Your garden is safe."],
        "dailyspin.result.weed.title":     ["de": "Unkraut entdeckt!",                               "en": "Weed Spotted!"],
        "dailyspin.result.weed.subtitle":  ["de": "%@ braucht deine Aufmerksamkeit.",                "en": "%@ needs your attention."],
        "dailyspin.result.coins.title":    ["de": "+200 Münzen!",                                    "en": "+200 Coins!"],
        "dailyspin.result.coins.subtitle": ["de": "Super Start in den Tag!",                         "en": "Great start to the day!"],
        "dailyspin.powerup.title":         ["de": "Power-Up verfügbar",                              "en": "Power-Up available"],
        "dailyspin.powerup.subtitle":      ["de": "Garantiert Grün — kein Unkraut möglich",          "en": "Guaranteed Green — no weeds possible"],
        "dailyspin.powerup.button":        ["de": "Nutzen",                                          "en": "Use"],

        // MARK: Stufen Labels
        "stufe.bronze1":                   ["de": "Bronze I",    "en": "Bronze I"],
        "stufe.bronze2":                   ["de": "Bronze II",   "en": "Bronze II"],
        "stufe.bronze3":                   ["de": "Bronze III",  "en": "Bronze III"],
        "stufe.silber1":                   ["de": "Silber I",    "en": "Silver I"],
        "stufe.silber2":                   ["de": "Silber II",   "en": "Silver II"],
        "stufe.silber3":                   ["de": "Silber III",  "en": "Silver III"],
        "stufe.gold1":                     ["de": "Gold I",      "en": "Gold I"],
        "stufe.gold2":                     ["de": "Gold II",     "en": "Gold II"],
        "stufe.gold3":                     ["de": "Gold III",    "en": "Gold III"],
        "stufe.diamant1":                  ["de": "Diamant I",   "en": "Diamond I"],
        "stufe.diamant2":                  ["de": "Diamant II",  "en": "Diamond II"],
        "stufe.diamant3":                  ["de": "Diamant III", "en": "Diamond III"],
    ]
}
